### ISSUE TITLE
Port tutorial to Vue

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#1]
**Update Jun 13**
Thanks to @mattrothenberg we have the example UI code ported to Vue. 🤙
[Vue UI example code](https://github.com/mattrothenberg/learnstorybook-vue)

**Contributors wanted**
Port the prose to Vue. This is mostly find & replace in Markdown with a bit of extra explanation for Vue-specific concepts.

**Comment by mattrothenberg** [comment]
@domyen I can give it a shot. Is there a more concrete ask beyond "converting the LearnStorybook example code" to Vue?

**Comment by mattrothenberg** [comment]
Ahh, that's a much larger undertaking than I had anticipated. Let me take a peek at the code (in earnest) and holler whether I can complete this in a reasonable timeframe.

**Comment by domyen** [comment]
Yup, the example "app" is 3 components with state tied into one of them. 
I guess app would be a misnomer. It's a screen composed of 3 components 😉

**Comment by mattrothenberg** [comment]
Oh, I'll give that a shot. Stay tuned.

**Comment by mattrothenberg** [comment]
So upon closer inspection, I'm not sure if it's possible to document (with Storybook) Vue components that rely on a Vuex store for fetching & updating data. Here's my rationale: 

Unlike Redux, the Vuex store must be injected into the parent Vue instance, via something like:
```js
import store from "./store";
new Vue({
  store,
  render: h => h(App)
}).$mount("#app");
```
With Storybook, we can't access this parent Vue instance. Which means that we can't inject different variants of the store into the different component scenarios we wish to document. With Redux, you can circumvent this problem by stubbing different `<Provider>` components and decorating each story with a different one.

**Comment by mattrothenberg** [comment]
@domyen All done. Built storybook is deployed to https://focused-montalcini-567535.netlify.com/.

Take a look at `master` of that repo I shared and let me know how best to proceed.

**Comment by mattrothenberg** [comment]
@tmeasday Fantastic suggestions. 

I've tried my best to incorporate all of this feedback, though I'm sure I've inevitably messed a few things up :) Check out `master` and let me know what you think, or send a PR through.

Thanks again!

**Comment by tmeasday** [comment]
@mattrothenberg looks great! I think we need to now figure out how to make the site switchable between view layers and how to do the text between different versions. Leave it with us for a few days. Thanks!

**Comment by tmeasday** [comment]
I made a start on the text: https://github.com/hichroma/learnstorybook.com/pull/34

I've been rewriting the code (to be one commit per section of the text) here: https://github.com/hichroma/learnstorybook-code/commits/vue

Maybe that part is overkill, but it is useful to check the intermediate instructions actually work!

**Comment by mattrothenberg** [comment]
No worries!

Emitting from the template (instead of calling a method defined in the component) certainly works, though IMO it makes the template difficult to read. Where possible, I try to keep my templates free of logic and other implementation details, deferring to computed properties & methods...

Either way, your guide is looking solid. Keep up the great work!

**Comment by domyen** [comment]
🤝Merged – excellent work folks!
