### ISSUE TITLE
composite-component.md line 248 unclear

### ISSUE THREAD

**Issue by ryan-stephen** [chromaui/learnstorybook.com#103]
> 248  Notice as well that this test is quite brittle. It's possible that as the project matures, and the exact implementation of the `Task` changes --perhaps using a different classname or a `textarea` rather than an `input`--the test will fail, and need to be updated.

Need more clarity about this line. I can work on enhancing this line if the intended meaning was conveyed.

**Comment by tmeasday** [comment]
Hi @ryan-stephen -- it refers to the fact that the test's verification step depends on some details of the HTML implementation that are not integral to the behaviour of the component (the fact that it's an `input` DOM element for instance). This dependency in the test makes it brittle and harder to maintain

**Comment by ryan-stephen** [comment]
Thank you @tmeasday -- I'll see if I can simplify it.
