### ISSUE TITLE
error while using requireContext

### ISSUE THREAD

**Issue by jsmasterathul** [chromaui/learnstorybook.com#107]
Once we start to use requireContext  in  .storybook/config.js, running the storybook is giving me an error, I was following the exact steps mentioned in tutorial.

<img width="1680" alt="Screenshot 2019-06-14 at 2 51 28 PM" src="https://user-images.githubusercontent.com/10139957/59498952-09222180-8eb4-11e9-9c36-480e35d8c1cd.png">

if I start to use `const req = require.context('../src', true, /.stories.js$/);`, the stuffs work fine

PFB my package.json

```
{
  "name": "taskbox1",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@storybook/addon-actions": "^5.1.7",
    "@storybook/addon-links": "^5.1.7",
    "@storybook/addon-storyshots": "^5.1.7",
    "@storybook/addons": "^5.1.7",
    "@storybook/react": "^5.1.7",
    "react-test-renderer": "^16.8.6",
    "require-context.macro": "^1.0.4"
  }
}
```

node version : v10.13.0
yarn version: v1.15.2

**Comment by omerg** [comment]
Same here.

**Comment by kylesuss** [comment]
@jsmasterathul I tried to reproduce this, but I am not seeing an issue. I'm thinking that there are probably a few ways that could have arrived at this point -- Can you describe your workflow for seeing this error? Were you following the guide and bootstrapping the app yourself? Did you clone the project from the example site (https://github.com/chromaui/learnstorybook-code) at a specific commit? I want to be able to trace your steps a bit more.

**Comment by jsmasterathul** [comment]
@kylesuss


I tested with the below versions of storybook (the github url you shared ) with me and things worked fine
"@storybook/addon-actions": "^5.0.0-rc.10",
    "@storybook/addon-knobs": "^5.0.0-rc.10",
    "@storybook/addon-links": "^5.0.0-rc.10",
    "@storybook/addon-storyshots": "^5.0.0-rc.10",
    "@storybook/addons": "^5.0.0-rc.10",
    "@storybook/react": "^5.0.0-rc.10",


I could conclude  "@storybook/addon-actions": "^5.1.7",
    "@storybook/addon-links": "^5.1.7",
    "@storybook/addon-storyshots": "^5.1.7",
    "@storybook/addons": "^5.1.7",
    "@storybook/react": "^5.1.7",

doesn't work with 'require-context.macro', probably would need an update in the doc, on how to load the context with new version of storybook



 I haven't cloned the repo, I was following the steps mentioned in tutorial.

**Comment by jsmasterathul** [comment]
version 5.1.7 is not compatible with require-context.macro, that is the version that gets installed when you follow the docs. thanks

**Comment by jsmasterathul** [comment]
current version 5.1.9 works fine. thanks

**Comment by skondiloza** [comment]
Hi can you please update this post because it is so annoying when you follow steps and end up with errors. After so much time I figure that problem is missing dependencies. You need to install @babel/core and babel-loader for this to work. You said in your text that we need to use babel macro, and if that should make as know that we need to install this dependencies it is very unclear. So please add this two install commands in your text for future readers.

**Comment by skondiloza** [comment]
Hi again it seams that this fix is broken next section because then when I tried this new test on TaskList I got conflict on that babel-loader versions. And solution is to add specific version there, so instead of just adding babel-loader it has to be babel-loader@8.0.5
