### ISSUE TITLE
Request: Angular project src

### ISSUE THREAD

**Issue by msegmx** [chromaui/learnstorybook.com#110]
Sorry, but I can't find the Angular version of the code, despite [this](https://github.com/chromaui/learnstorybook-code/pull/4).

Could someone please help with providing a link to the Angular code for the [tutorial](https://www.learnstorybook.com/angular/en/get-started)?

**Comment by kylesuss** [comment]
@msegmx I believe this is what you are looking for:

https://github.com/chromaui/learnstorybook-code/tree/angular

There is a separate branch for the angular code. Does that help?

**Comment by msegmx** [comment]
Yess, thanks a lot!
