### ISSUE TITLE
Spanish version 

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#12]
This is the discussion for the Spanish version of Learn Storybook. Use this issue to divvy up translation, request feedback, etc. For more info about the translation project and to get involved checkout #3 

Please target your PRs at branch [`language-spanish`](https://github.com/hichroma/learnstorybook.com/tree/language-spanish). 🙏

cc @icarlossz and @luchux

**Comment by icarlossz** [comment]
All right. 👨🏻‍💻

**Comment by luchux** [comment]
@icarlossz Querés que traduzca todos los capítulos que quedan, desde el último que aceptaste en el PR, hasta el final? Vos después podes hacer la revisión, los fixes, y aceptar el PR. 

Así terminamos de una. Yo estoy bastante al pedo, idle, estos días y me gustaría ir cerrando esto. 

Salutes bro.

**Comment by icarlossz** [comment]
Ando igual ahora mismo yo, si querés sigamos como veníamos de uno a uno y cada uno le hace code review al otro. Contame si te parece.

**Comment by luchux** [comment]
dale!
Cómo estamos el último? jaja, ya me perdi

**Comment by icarlossz** [comment]
Complete and proofread Spanish translation without problems.  🔥

**Comment by domyen** [comment]
This is awesome @icarlossz and @luchux! @tmeasday and I are currently working on the associated changes to support this in #28. Should have a path forward by end of week. I'll aim to release the Spanish version sometime next week.

**Comment by icarlossz** [comment]
Awesome! 💯

**Comment by luchux** [comment]
Buena cabro!

Awesomeness 100% !

**Comment by domyen** [comment]
We released a first cut of the Spanish version to master ([link](https://www.learnstorybook.com/react/es/get-started/))! 
There will likely be a few tweaks necessary. Let's test and let it settle for a few days.

Known issues:
- Twitter message is not translated (it's currently a part of the template not content)
- Language picker can be hard to find

**Comment by luchux** [comment]
Should we may be translate as well some images? Can send texts for them. 
i.e. attached

![](https://www.learnstorybook.com/storybook-relationship.jpg)

**Comment by icarlossz** [comment]
@domyen You have the assets of the images for translate them, too? 🤓

**Comment by domyen** [comment]
Closing this. Keeping track of all the image versions is probably out of scope right now because it adds more maintenance surface area. I want to make releasing new editions and updates as easy as possible for contributors. 🙏
