### ISSUE TITLE
Review Design Systems for Developers guide

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#137]
@tmeasday and I are creating a new Storybook guide! 🎉 It'll be launched with the website refresh that @kylesuss is working on [here](https://github.com/chromaui/learnstorybook.com/pull/106).

**Overview**
“Design systems for developers” is a free 9-chapter guide that teaches professional developers about the design system infrastructure and production workflows used by the smartest frontend teams. It focuses on Storybook and includes real code + example repositories.  

**Feedback areas**
General feedback is definitely appreciated. Here are some specific areas that could use extra attention:
- Logical consistency: Does it make sense?
- Syntax and grammar: Does it conform to the standards of the English language?
- Tone and flow: Is it enjoyable to read?
- Code samples: Is code sensible and skim-able while reading?

**[👉Read the preview here👈](https://docs.google.com/document/d/17DtQ_GXYjV7VxuO5sTqvkkd7BYvzrTIUuA9ql0IoUZ0/edit)**

We'd love early feedback from contributors 🙏 
@jonniebigodes @icarlossz @alterx @luchux @danielduan @chinanf-boy

**Comment by jonniebigodes** [comment]
@domyen i've been following the awesome work @kylesuss been doing in the preview and it's looking awesome. If you don't mind i'll go over it tonight and during the weekend and i'll report back. Sounds good?

**Comment by domyen** [comment]
For sure, thanks Jonnie! 🙇‍♂️

**Comment by jonniebigodes** [comment]
i've gone through it and left in some comments. But asides from that, nice effort on your part on creating such a really well written and essential piece of documentation, that's also easy to follow. 

Can't wait to see this published and available. 

@domyen and @tmeasday i would like to thank you both for your effort in putting this together.

**Comment by danielduan** [comment]
Looks pretty good! I put some thoughts there as well.

**Comment by domyen** [comment]
This is now published. Thanks folks 🙇

**Comment by jonniebigodes** [comment]
@domyen no need to thank, glad that i was able to provide some insights and contribute to it. Going to check it out shortly and start working on the translations
