### ISSUE TITLE
A couple of quick questions

### ISSUE THREAD

**Issue by jonniebigodes** [chromaui/learnstorybook.com#138]
This one has been on the back burner for quite some time and sorry for that.
Here are the questions:

- While i was working in translating the documentation, one thing kept me wondering and that was about the `addons` section, react has it but vue and angular doesn't, is this section left out by omission, probably due to the fact that probably no one made a pr for it? Should it be a good thing to revisit this and try and standardize the whole documentation? More even now that #91 is currently underway.

- I was thinking about having a copy code snippet button added to the documentation, is this doable in a near future? After the refresh of the site is gone through and possibly expand it to  #137. 

Feel free to provide feedback 

Thanks in advance

**Comment by domyen** [comment]
Great questions. 
- Omission wasn't intentional. We're definitely looking for help to translate those sections and for more help in Vue and Angular (both for this guide and in Storybook itself).
- Good idea. Would totally welcome a PR that adds a copy button to the syntax highlight.

I know we have a [syntax highlighter](https://storybook-design-system.netlify.com/?path=/docs/design-system-highlight--all-languages) component in the Storybook Design System (which this project uses), but I think there was a hiccup integrating it for some reason. cc @kylesuss

**Comment by kylesuss** [comment]
@jonniebigodes I think a safe approach would be to add the feature to the [`Highlight` component in the design system](https://github.com/storybookjs/design-system/blob/master/src/components/Highlight.js). The end goal is to have that component be apart of the design system & able to be used in any client application. There was just a difference in how some of the clients implemented it, so I couldn't actually import that component into all of the client apps yet. It wasn't as big of an issue for `learnstorybook.com` though.

In the PR for the new layout, I am importing the `Highlight` component into `learnstorybook.com`:

https://github.com/chromaui/learnstorybook.com/blob/3077244289207c9deed092fc560a9da56b726e70/src/components/screens/ChapterScreen/index.js#L5

If you add the logic in the `Highlight` component in the design system, it should be accessible in the new layout work for `learnstorybook.com` once a new release of the design system is shipped.

Sound ok?

**Comment by jonniebigodes** [comment]
@kylesuss sounds excelent. Once again, you've been doing a really awesome job with this implementation.

@domyen regarding the code in this repo for vue i'm currently testing some things out and i'm going to create a issue and we can go over it afterwards. Sounds good? 

Also as a side note that i forgot to ask when i commented out in #137 and if you can share some insights on it. Do you plan to release it like in this repo and do you want translations for it?

**Comment by domyen** [comment]
@jonniebigodes We plan to release the guide as part of LearnStorybook! Would love and appreciate translations! 🙇‍♂️

**Comment by jonniebigodes** [comment]
@domyen ok...i've been checking the commits being made to the next branch. As soon as it's relased i'll start working on it
