### ISSUE TITLE
Storysource Webpack rule causing build errors in Design Systems for Developers [REACT]

### ISSUE THREAD

**Issue by jpmarra** [chromaui/learnstorybook.com#155]
### Description
When I followed the instructions for adding `webpack.config.js` into `.storybook`, which pushes the loader rule for `addon-storybook`, it caused the build to error in every `.stories` file with the error `Import in body of module; reorder to top  import/first`.

After researching the issue, I found that this comment seems to solve the problem: https://github.com/storybookjs/storybook/issues/6974#issuecomment-499903328

### Proposed Change

Original:
```javascript
//And update your webpack config in .storybook/webpack.config.js:

module.exports = function({ config }) {
 config.module.rules.push({
   test: /\.stories\.jsx?$/,
   loaders: [require.resolve('@storybook/addon-storysource/loader')],
   enforce: 'pre',
 });

 return config;
`};
```

Fixed: 
```javascript
//And update your webpack config in .storybook/webpack.config.js:

module.exports = function({ config }) {
 config.module.rules.unshift({
   test: /\.stories\.jsx?$/,
   loaders: [require.resolve('@storybook/addon-storysource/loader')],
   enforce: 'pre',
 });

 return config;
`};
```

**Comment by domyen** [comment]
thanks @jpmarra (just invited you to collaborate too)

**Comment by tmeasday** [comment]
Seems to work! Thanks so much @jpmarra, this was something that had bugged me a bit.

**Comment by qoalu** [comment]
Can you update the docs with this?

**Comment by jonniebigodes** [comment]
@qoalu i think that the tutorial is correct, the issue lies with the readme in the addon itself. Should you be interested open a pull request in the storybook repo with the change above, so that not only the people that read the tutorial benefit from this, but the rest of the community. What do you think @tmeasday  and @domyen ?

**Comment by domyen** [comment]
Agree with @jonniebigodes. Can you open up a PR in the SB repo @qoalu? I can help with reviewing it there.
