### ISSUE TITLE
MDX integration causes build error 

### ISSUE THREAD

**Issue by jpmarra** [chromaui/learnstorybook.com#165]
### Description
When following the Documentation steps in Design Systems for Developers, I came across a build error with `@babel/parser` when I changed the config to import the new mdx file `Avatar.stories.mdx`

Via the instructions [here](https://www.npmjs.com/package/@storybook/addon-docs), adding `babel-loader` as a dev dependency seems to solve the issue. Not sure if this is 100% needed but I wasn't able to get it working without it.

### Error
![Screen Shot 2019-10-07 at 2 50 44 PM](https://user-images.githubusercontent.com/22504731/66340285-d85a7200-e912-11e9-87b4-a72d35eee3c2.png)

### Proposed Change

Add `yarn add -D babel-loader` as a step when integrating MDX.

**Comment by dstroot** [comment]
I had the same issue last night - since it was late I gave up went to bed.  I’ll give this a try.  I was bummed not to be able to get MDX to work!

**Comment by tmeasday** [comment]
That's weird, I've not seen that before. @jpmarra / @dstroot I assume you've been following the guide as written? Can you post the versions of the various SB packages you are using? And the `react-scripts` version?

By best guess would be maybe the version of `@storybook/docs` you used maybe was out of sync with the other SB packages? 

@shilman I think you'd be best to take a look at this. We can of course add the `babel-loader` line (and maybe should in the short term), but it shouldn't be necessary, right?

**Comment by jpmarra** [comment]
@tmeasday You were correct. It seems that `@storybook/addon-docs` was on `5.2.3` while the other SB packages were on `5.2.1`. 
![Screen Shot 2019-10-08 at 10 36 05 AM](https://user-images.githubusercontent.com/22504731/66410170-abb06400-e9bf-11e9-83f7-6deaf5181abf.png)

After updating the SB packages, and removing `babel-loader` as a dev dependency, I am no longer receiving any build errors and the page renders as expected. Whats strange is that I'm still getting a warning of an unmet peer dependency of `babel-loader` when doing a fresh install.
<img width="883" alt="Screen Shot 2019-10-08 at 11 33 05 AM" src="https://user-images.githubusercontent.com/22504731/66410282-db5f6c00-e9bf-11e9-9de6-ac151d184749.png">

**Comment by tmeasday** [comment]
That is surprising, I would have thought either `sb init` would add that or `react-scripts` would depend on it. Perhaps a separate SB issue?

**Comment by horacioh** [comment]
the problem here is solved if you set some options on `.storybook/presets.js` file:
https://github.com/storybookjs/storybook/blob/master/addons/docs/README.md#preset-options

working on a PR to add this to the docs :)

**Comment by grahamcrackers** [comment]
I was going through this tutorial last night and I just wanted to confirm that adding the following snippet did allow mdx to work for me.
```
module.exports = [
  {
    name: '@storybook/addon-docs/react/preset',
    options: {
      configureJSX: true,
    },
  },
];
```

**Comment by horacioh** [comment]
yeah @grahamcrackers, this code solved it for me! :)

**Comment by jonniebigodes** [comment]
@tmeasday safe to assume that this can be closed correct. As of 6.0 and the tutorial updates we're now not mentioning this and docs addon has become "mainstream" with Storybook
