### ISSUE TITLE
Avatar MDX file not included in build

### ISSUE THREAD

**Issue by jpmarra** [chromaui/learnstorybook.com#177]
I noticed that when the design system is built, it leaves the `Avatar.stories.mdx` file out of the build. This leaves this component out of the UI of the app.

This seems to be the case in the screenshot in the Distribute docs as well:
<img width="1119" alt="example-app-storybook-with-design-system-stories" src="https://user-images.githubusercontent.com/22504731/66513824-f0182e80-eaa9-11e9-9fb3-f03b962aae42.png">

How do we go about getting the mdx file included in the build?

**Comment by tmeasday** [comment]
Maybe we need to include a flag so babel copies the `mdx` file across to the `dist` folder unchanged? Although that relies on the user having the proper mdx setup in their Storybook to be able to import it.

TBH this particular way of importing one storybook into another is problematic (for reasons like this) and we'd like to get a better, first class way into SB eventually. It's something @ndelangen has been looking at a little bit recently (and presented at the last maintainer meeting).

**Comment by stephyswe** [comment]
**STARTPOINT**
https://www.learnstorybook.com/design-systems-for-developers/react/en/distribute/

**SECTION** 
Prepare your design system for export

> To build the package, we’ll add a script to package.json that builds our source directory into dist:

```
{
  "scripts": {
    "build": "BABEL_ENV=production babel src -d dist",
      ...
  }
  "babel": {
    "presets": [
      "react-app"
    ]
  }
}
```

This can be done with ---copy-files flag which copies all files in src into dist folder. 

Todo so replace 
`"build": "BABEL_ENV=production babel src -d dist",`
WITH
`"build": "set BABEL_ENV=production&& babel --copy-files src -d dist",`

**REMANING ISSUE(S)**
**1. --copy-flag works but it seems to add entire app to npm package.**
-A fix could be to copy all info in .gitignore into .npmignore and replace "dist" with "src" 
Currently working to resolve this issue.   
_More info about npmignore: https://docs.npmjs.com/using-npm/developers.html_

2. Storybook doesn't read external usage of .MDX files
This is real issue. I don't know it happens.. developers of Storybook could you look into this?

Scenario: Added .MDX files to npm package and when adding (.js.mdx) require*, then starting Storybook - "yarn run storybook" - an error message is shown.

*:
.storybook/config.js
```
// automatically import all files ending in *.stories.js
configure(
  [
    require.context('../src', true, /\.stories\.(js)$/),
    require.context(
      '../node_modules/xxx-learnstorybook-design-system/dist',
      true,
      /\.stories\.(js)$/,
    ),
  ],
  module,
);
```

**DISUSSIONS**
It's January, soon February. This issue hinders usage of MDX files in Storybook Design System. I believe others solve this issue and if you know a solution, please provide useful info in this issues thread. Than you kindly.

**AUTHOR**
Stephanie

**Comment by stephyswe** [comment]
Seems there is an answer @ https://github.com/chromaui/learnstorybook.com/issues/165



> ### Description
> When following the Documentation steps in Design Systems for Developers, I came across a build error with `@babel/parser` when I changed the config to import the new mdx file `Avatar.stories.mdx`
> 
> Via the instructions [here](https://www.npmjs.com/package/@storybook/addon-docs), adding `babel-loader` as a dev dependency seems to solve the issue. Not sure if this is 100% needed but I wasn't able to get it working without it.
> 
> ### Error
> ![Screen Shot 2019-10-07 at 2 50 44 PM](https://user-images.githubusercontent.com/22504731/66340285-d85a7200-e912-11e9-87b4-a72d35eee3c2.png)
> 
> ### Proposed Change
> Add `yarn add -D babel-loader` as a step when integrating MDX.

**Comment by jonniebigodes** [comment]
@stephyswe i've skimmed through the existing documentation and it seems that there are still some lingering issues, as it's not accurate, there are some things that need to be addressed as with the recent release of 5.3 with new configuration available. It's my belief that the team behind Storybook focused on the development and release of the said version to make not only the configuration more approachable, leaner and simpler to use. And the documentation would be rolled out incrementally as soon as all items are vetted to avoid misleading the readers. I think that this is going to be fixed shortly.

**Comment by tmeasday** [comment]
I'm still not sure what we should do about this one. I think I am OK with the mdx stories not appearing when imported, given we have a better solution to this problem coming in 6.0. I don't think we should encourage people to publish their mdx files as it'll cause all end of incompatibility problems when imported into SBs that don't include MDX.

What do people thing?

**Comment by domyen** [comment]
@tmeasday do you mean exporting them with the design system package and then importing them into consumer apps?

**Comment by tmeasday** [comment]
@domyen, yes right now we transpile the `.stories.js` files and place them inside the package that is published to npm. This allows consumers to import those stories without needing to share babel configs etc with the author of the npm package.

So far so good. But when it comes to mdx, there is no babel plugin you can use to compile it to ES5, as the storybook mdx loader has a bunch of smarts that run at load time. So we'd have to ship them in the npm package unmodified, which would then mean if someone was to import them they'd have to have a similar webpack/babel setup to the package author. It might work in a lot of cases but it would be serious confusing when it didn't.

This will be fixed with the composition feature which uses a different approach that avoids these problems.

**Comment by jonniebigodes** [comment]
@tmeasday it's now safe to assume that this as become outdated and can now be closed, correct.

Feel free to provide feedback

**Comment by tmeasday** [comment]
I think so!
