### ISSUE TITLE
Link languages on GuideScreen to respective guides

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#192]
Link the languages listed on guide screen to their respective guides. This makes the languages more discoverable and saves non-English speakers from extra clicks. 

<img width="730" alt="Screen Shot 2019-10-16 at 10 19 33 AM" src="https://user-images.githubusercontent.com/263385/66927877-91e5d100-effe-11e9-847b-83a069b62185.png">

**Comment by jonniebigodes** [comment]
@domyen i'm going to make a pull request soon addressing this issue. Also one thing before i proceed further, do you want the component story files updated as well?

**Comment by domyen** [comment]
Yea! Since we do Component-Driven Development the [Hero component's](https://www.chromaticqa.com/component?appId=5cf841a3f3e3d200208ffc74&name=Screens%7CGuideScreen%2FHero&buildNumber=198&specName=default) story should get updated to reflect the new behavior.

**Comment by jonniebigodes** [comment]
@domyen i'll do the final round of checking tomorrow as it's almost 2 am where i'm at. And create the pr detailing what i've done. Sounds good?

**Comment by jonniebigodes** [comment]
Fixed with #204
