### ISSUE TITLE
Angular code

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#2]
Angular users, we need your help converting the [LearnStorybook example code](https://github.com/hichroma/learnstorybook-code). 🙏 

The example is currently written in React and Redux. If you use Angular (and a little React) and have a grasp on its state management ecosystem help us introduce Storybook to that community.

Comment below!

**Comment by alterx** [comment]
Hey @domyen, I helped bringing Angular to Storybook and would love to contribute here. I've also done a ton of React work so it shouldn't be an issue to convert the code :) 

I don't have a lot of free time but will start looking into the code. Is there anything I should know before starting?

**Comment by tmeasday** [comment]
Hey @alterx, great to hear from you!

I'm glad you asked. I've been (slowly) looking at trying to get the Vue version integrated as contributed by @mattrothenberg broken up into steps to match our chapters (see 
https://github.com/chromaui/learnstorybook.com/issues/1#issuecomment-397947421)

The thing that takes a little while is just getting every step working in a simple reproducable way for users. In particular the first chapter where you run a few commands and end up with working app and storybook and jest environment---this wasn't quite as easy in Vue as it was in React (at least for me, who isn't a Vue user).

So basically what I am trying to say is there are a few levels of work that need to be done:

1. Getting the final app&storybook as per https://github.com/chromaui/learnstorybook-code running in an angular environment w/ equivalent code (e.g. replacing Redux w/ something that makes sense for angular, etc). This bit I definitely can't do myself and is the most important!

2. Getting the code from above broken up into commits that match up with the chapters and are easy for the user to follow with simple steps. I appreciate this is a pain and I am happy to do it myself although I suspect you will be better at it than me!

3. Writing the corresponding text to 2. This is easier to do at the same time as 2, but also I am more than happy to do it.

Does that make sense? Please hit me up here or on storybook slack if there are any specific questions!

**Comment by alterx** [comment]
Hey @tmeasday, long time no see (chat 😂) !

I like the idea of having a commit per title, it feels like it's going to help a lot. As of the work that needs to be done, I intend to work on the three parts. It's probably easier (and just faster) for the person that wrote the app to work on 2 and 3.

I'll start with the app and hit you up on Slack if I have further questions :)

**Comment by alterx** [comment]
The code is here https://github.com/chromaui/learnstorybook-code/pull/4
Will also add changes for the site on this repo.

**Comment by domyen** [comment]
Thank you @alterx! 🙏 Closing this ticket
