### ISSUE TITLE
Clarity in Design Systems for Developers tutorial

### ISSUE THREAD

**Issue by jgerlach** [chromaui/learnstorybook.com#202]
On the [Build](https://www.learnstorybook.com/design-systems-for-developers/react/en/build/) step of the tutorial when explaining about GlobalStyles and the `addDecorator` function it never actually says where to add the code. I ended up adding it to the `config.js` and that worked, but it doesn't tell you to do that in the tutorial. In the actual Docs on [Decorators](https://storybook.js.org/docs/addons/introduction/#1-decorators) that is actually what is suggested to do. 

Wording should be added that says something like "For this tutorial we will add this code to the `./storybook/config.js` file."

**Comment by jonniebigodes** [comment]
@jgerlach i missed that one when i was proofreading. But i'm a little biased as i'm knowledgeable of how Storybook handles Decorators. 
Reading the section in question, i understood where it should be placed. But for a new person that comes into contact with Storybook via this tutorial, it might be a bit misleading on where the code should be placed. 
Probably a better wording that might handle the issue you're experiencing could be something like:

> To use the GlobalStyle “component” in Storybook, we can make use of a decorator (a component wrapper). In an app we’d place that component in the top-level app layout. But for our case we're going to add it to our `./storybook/config.js`

And update the code with a reference to the file, like the following: 
```javascript
//./storybook/config.js
.... rest of the code
```

@domyen @tmeasday thoughts on this?

**Comment by domyen** [comment]
That's a good catch @jgerlach. I support that proposal 👍 @jonniebigodes.

**Comment by jgerlach** [comment]
That's exactly what I was thinking 👍

**Comment by jgerlach** [comment]
Just below that You might want to say that to add the font link that we will create the file called `preview-head.html` since it doesn't already exist when you pull the files with svn.

**Comment by jgerlach** [comment]
Should I create a new issue for each typo I find, or should I create a list of them in a single issue?
![Screen Shot 2019-10-23 at 10 49 53 AM](https://user-images.githubusercontent.com/1945808/67420299-99235680-f58b-11e9-9573-43d15fe71d08.png)

**Comment by jonniebigodes** [comment]
@jgerlach regarding:

> Just below that You might want to say that to add the font link that we will create the file called preview-head.html since it doesn't already exist when you pull the files with svn.

Probably a better rewording would be something like:
"Our design system also relies on the font Nunito Sans to be loaded into the app. The way to achieve that in an app, depends on the app framework (read more about it here), but in Storybook the easiest way to achieve that is to create the file `.storybook/preview-head.html` if it doesn't exist and add the following content, so that the font can be used correctly(safely???) in our design system".

regarding this:
> Should I create a new issue for each typo I find, or should I create a list of them in a single issue?


I think that a list of issues would be a better approach for this instead of individual issues, so that they can be better triaged and addressed. 

Once again @domyen thoughts?

**Comment by domyen** [comment]
I agree with @jonniebigodes re:list of issues. That way we can tackle them
all at once.

>

**Comment by jgerlach** [comment]
@jonniebigodes I think It's actually explained pretty well in the main docs so you can have a link back to them. How about this? 

> Our design system also expects the font Nunito Sans to be loaded into the app. How fonts are loaded into an app depends on the app framework (read more about it [here](https://github.com/storybookjs/design-system#font-loading)), but in Storybook the easiest way to load a font is to is to create the file `.storybook/preview-head.html`  if it doesn't exist and add the following content to load it into our app:

After the `<link ...>` I would add a link to the docs on how the `preview-head.html` file works.

> Read more [here](https://storybook.js.org/docs/configurations/add-custom-head-tags/#docs-content) on how you can use the `.preview-head.html` file to inject different tags into the HTML head.

The docs page has a really good explanation, although you might want to add that it's also a good way to inject font tags.

**Comment by jonniebigodes** [comment]
Sounds good to  me. Add this also the list we discussed earlier so that we can start tackling them and improve the docs.

**Comment by jonniebigodes** [comment]
@jgerlach thank you for bring this to our attention, i'm going to close the issue. With #380 the Design Systems for Developers tutorial was updated and your feedback was incorporated into it. 

Stay safe
