### ISSUE TITLE
Add chapter on integrating add-ons using knobs as an example

### ISSUE THREAD

**Issue by kylemh** [chromaui/learnstorybook.com#21]
Many people would benefit from a tutorial on add-on integration
Many people would love knobs (very widely utilized add-on)

I'm down to work on content. Just wanted to make sure this is something that's desired.

**Comment by tmeasday** [comment]
Potentially it also makes sense to have a (separate) addendum on "creating
documentation with Storybook" that explains a few of the docs-style addons
(like info/storysource/etc)
