### ISSUE TITLE
Angular documentation includes a React screenshot

### ISSUE THREAD

**Issue by geromegrignon** [chromaui/learnstorybook.com#213]
The [Get Started](https://www.learnstorybook.com/intro-to-storybook/angular/en/get-started/) part of the Angular version of the documentation includes a screenshot of a react starter page.

As it's a .png composed with 2 other screenshots (command line and storybook starter), does one of the maintainers still have the original screenshots to make a new version for Angular?

If needed, here is a link to an Angular starter page to make the missing screenshot : https://nostalgic-noether-13b323.netlify.com/

**Comment by domyen** [comment]
@geromegrignon thanks for the link, very helpful 🙇 

Would something like this work:
![image](https://user-images.githubusercontent.com/263385/68532050-27ffd500-02e7-11ea-9527-b0465d0f85fe.png)

**Comment by jonniebigodes** [comment]
@geromegrignon and @domyen the angular tutorial is being rewritten as i type this. There are some key items that need to be addressed and that was one of them. I'm going to copy over the image and use it if you both don't mind. Sounds good?

**Comment by geromegrignon** [comment]
Sounds good for me.
@jonniebigodes  don't hesitate if you need help for the angular tutorial. I just started to review the existing tutorial to clean it up before working on french translation but i'll stop for now.

**Comment by domyen** [comment]
Perfect, thank you 🙇‍♂️
