### ISSUE TITLE
icon-star is not shown

### ISSUE THREAD

**Issue by soobing** [chromaui/learnstorybook.com#216]
Hi I am using css from [this link](https://github.com/chromaui/learnstorybook-code/blob/master/src/index.css) as written in document.
![image](https://user-images.githubusercontent.com/16860535/68562354-a5b11580-048c-11ea-8d75-0cb925a5972a.png)

However the icon star is not shown. I think I need more link from css not only that link. This is not really critical and unimportant but I want to fix it. Whatever documents or css. Thanks if you give me any comments please.
* currently shown in my localhost
![image](https://user-images.githubusercontent.com/16860535/68562332-887c4700-048c-11ea-93d1-c336104d92fb.png)

**Comment by soobing** [comment]
![image](https://user-images.githubusercontent.com/16860535/68565802-ea8e7980-0497-11ea-9ec1-c41a65092a02.png)
I think every icon shown like that

**Comment by geromegrignon** [comment]
Keep reading the tutorial. The next step is to add icon assets to your project.

**Comment by soobing** [comment]
> Keep reading the tutorial. The next step is to add icon assets to your project.

Opps Sorry I passed this section. Thanks for reply.
![image](https://user-images.githubusercontent.com/16860535/68591642-88079e80-04d4-11ea-8fc0-ab37e9cbf855.png)

**Comment by domyen** [comment]
Closing thanks @geromegrignon 🙇
