### ISSUE TITLE
Dutch translation appears as 'nl' not 'Nederlands'

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#217]
In the UI, Dutch should appear as 'Nederlands' and not the country code `nl`. 

@ghengeveld can you confirm that this is how the language is printed in Dutch (as a native speaker). See the screenshot below. 

<img width="415" alt="Screen Shot 2019-11-13 at 1 02 04 PM" src="https://user-images.githubusercontent.com/263385/68790839-16376e00-0616-11ea-94bb-15ac5a60afeb.png">

**Comment by kylesuss** [comment]
To have a display name, `nl` has to be added as a key here:

https://github.com/chromaui/learnstorybook.com/blob/master/src/lib/getLanguageName.js

**Comment by ghengeveld** [comment]
Yes it should be "Nederlands".
