### ISSUE TITLE
learn storybook in angular

### ISSUE THREAD

**Issue by sipuxd** [chromaui/learnstorybook.com#227]
I'm trying to build out a composite component in the angular storybook tutorial https://www.learnstorybook.com/intro-to-storybook/angular/en/composite-component/

In the "Build out the states" section it wants me to import { Task } from './task.model'; however, the tutorial did not have me build a task.model..... I even looked in the code to keep synced with the chapter and it also does not have the task.model ?

I'm unable to complete the tutorial until I get this resolved it seems...?

What's up with the task.model ?

**Comment by geromegrignon** [comment]
Here is the Task model (from the previous section [**Simple Component**](https://www.learnstorybook.com/intro-to-storybook/angular/en/simple-component/))

![image](https://user-images.githubusercontent.com/32737308/70248994-0aa21780-177c-11ea-9539-ec88090564c6.png)

**Comment by jonniebigodes** [comment]
@sipuxd and @geromegrignon sorry for that, i've got some issues with angular and storybook that need to be addressed, so between testing it and modifying it, i put it on the back burner and moved on with svelte and a tutorial for react native that's currently under review. I hope i manage to have my issues fixed and mop up the rest of the documentation shortly.

**Comment by jonniebigodes** [comment]
@domyen and @tmeasday i'm going to close this as this is already solved with #228
