### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by calidan-x** [chromaui/learnstorybook.com#241]
https://www.learnstorybook.com/intro-to-storybook/react/en/using-addons/
In session **Adding A New Story To Avoid Regressions**

_longTitle_ should change to _longTitleString_

**Comment by jonniebigodes** [comment]
@calidan-x you're correct and thanks for bring it to the attention of the team. The documentation is currently being updated by the team in a effort on their end to make people start using a new simpler and more functional way to create stories. With that the documentation is being updated incrementally. Probably me or @tmeasday or @domyen will update it in the coming days. 

Sorry for the inconvenience.

**Comment by kylesuss** [comment]
Fixed in #240
