### ISSUE TITLE
Guides link dropdown in navigation is missing focus color.

### ISSUE THREAD

**Issue by Myoxocephalus** [chromaui/learnstorybook.com#253]
Some motivation for this:
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
When i use the page with only the keyboard and focus the Guides drop down i get no indication it´s active.
<img width="117" alt="Skärmavbild 2020-01-15 kl  07 02 11" src="https://user-images.githubusercontent.com/2316544/72411561-79a36080-376b-11ea-877b-bd6adff8188d.png">
Expected result could be something like team link.
<img width="74" alt="Skärmavbild 2020-01-15 kl  07 02 27" src="https://user-images.githubusercontent.com/2316544/72411576-8031d800-376b-11ea-8910-18ee3406fa41.png">

If you think it´s ok i can fix it and open a PR.

**Comment by domyen** [comment]
Hey @Myoxocephalus good find. Would be happy for you to open an PR for this – the code for this lives in the Tooltip component of the Storybook Design System. If you send one I can help merge it and update the deps here!

repo: https://github.com/storybookjs/design-system
published SB: https://storybook-design-system.netlify.com/?path=/docs/design-system-intro--page

**Comment by jonniebigodes** [comment]
Closing this for the time being. If anyone else wants to pick it up , more than glad to re-open it.
