### ISSUE TITLE
Update Storybook install guide

### ISSUE THREAD

**Issue by DaleSeo** [chromaui/learnstorybook.com#256]
I just realized that `npx -p @storybook/cli sb init` no longer generates `.storybook/config.js`. Instead, it creates `.storybook/main.js` as of Storybook v5.3.3. I suggest updating the following guide so that it doesn't mislead. For example, with the new setup, there is nothing we should do to get the sample stories indexed because it is already configured like `stories: ['../src/**/*.stories.js'],` in `.storybook/main.js`.

https://github.com/chromaui/learnstorybook.com/blob/0e65dd87d64b34bbe248f0df1d49c83a402170d5/content/design-systems-for-developers/react/en/build.md#install-storybook

In addition, it seems like the way to apply decorators globally has changed lately. According to [the Storybook doc](https://storybook.js.org/docs/basics/writing-stories/#decorators), `.storybook/preview.js` should be used.

**Comment by jonniebigodes** [comment]
@DaleSeo the documentation is currently being updated. There's a couple of prs addressing this situation. More specifically #251 and #249, be on the lookout as probably soon it will available.

**Comment by DaleSeo** [comment]
@jonniebigodes Oops! Sorry for opening this issue without looking through existing issues. You guys seem to be doing great! 👍

**Comment by jonniebigodes** [comment]
@DaleSeo no need to apologize. As i said before be on lookout as the documentation will be updated shortly.

**Comment by domyen** [comment]
Thanks for the heads up nonetheless @DaleSeo. Great job @jonniebigodes 🙇‍♂️
