### ISSUE TITLE
Vue Tutorial. Wire in data. Doesn't work.

### ISSUE THREAD

**Issue by sshiling** [chromaui/learnstorybook.com#265]
https://www.learnstorybook.com/intro-to-storybook/vue/en/data/
It doesn't work as described.
The reason is the store is registered for the Vue App, not for the StoryBook App.
So when I try to use store in my TaskList.vue  - I get an error:
"Cannot read property 'state' of undefined"
Here is the screenshot: http://i.shotnes.com/u/2778/0122/screenshot_5279.png

**Comment by sshiling** [comment]
This tutorial doesn't show how actually to use vuex with storybook,
After cloning TaskList into PureTaskList there's no information about the next vuex store use in TaskList. I found that it works as expected just after store import into TaskList component.
I add store to the default story. But how can I preset other stories (empty, loading, withPinnedTask) using my actual store?

**Comment by jonniebigodes** [comment]
@sshiling regarding this:

> This tutorial doesn't show how actually to use vuex with storybook,

It does show you how to use Storybook and Vuex. The tutorial's flow is incremental, you start small with a simple component, move into a composite component, add in a data management package, more specifically in this case `vuex` in the data section and sets the tone for the next section that is the screens section, in there it all coalesces into a "full blown app" in that section you're introduced on how you can use the decorators to add context to the stories you'll eventually create using Storybook. The way i see it when i first came into contact with Storybook and this repo and started working in the translations is that the author's intent in that section of the tutorial is to allow you a good experience with Storybook, allowing you, the reader to continue to see the work that you've been doing so far and with that avoid introducing errors and extra information and keep you engaged. And with that avoid "murking the waters"(pardon the bad pun). 

@domyen, @tmeasday thoughts?

**Comment by domyen** [comment]
💯@jonniebigodes is right. That's how the tutorial is structured.

**Comment by sshiling** [comment]
@jonniebigodes , @domyen , okay. Got it. 
I'm sure you know better how to do this tutorial.
It's just my thoughts about potential improvements.
