### ISSUE TITLE
Building storybook does not work on windows

### ISSUE THREAD

**Issue by tmeasday** [chromaui/learnstorybook.com#274]
As reported by @stephyswe on Discord: 

>>>
1.  Prepare your design system for export - BABEL_ENV needs "set" to work for Windows Users, also --copy-files to add .mdx files in /dist/ folder
REPLACE
{
  "scripts": {
    "build": "BABEL_ENV=production babel src -d dist",
WITH
{
  "scripts": {
    "build": "set BABEL_ENV=production&& babel src -d dist --copy-files",
...
>>>

**Comment by jonniebigodes** [comment]
@tmeasday i was reading this and why not use something like [crossenv](https://www.npmjs.com/package/cross-env) for this? I think it could offer some flexibility to the readers, not only windows based ones, but for macos and linux ones. To avoid making the readers having to explicitly set it. @stephyswe do mind sharing your input on this aswell?

**Comment by tmeasday** [comment]
Yeah, sure although I wanted to remind myself why setting the env var was needed in the first place.

**Comment by tmeasday** [comment]
This should be fixed by #276.
