### ISSUE TITLE
Add a banner indicating that a translation isn't updated to latest release

### ISSUE THREAD

**Issue by tmeasday** [chromaui/learnstorybook.com#275]
Based on a discussion in Discord with @stephyswe: 

I think maybe whenever we do a significant release of SB we should add banner to all translations saying "This guide has not been updated yet to SB@X -- if you can help, send a PR here: <>".

Then whenever someone submits a PR to update a translation to that version, that translation can also remove the banner. Probably we'd just have a config field with the version that the translation is known to work with.

WDTY @domyen @jonniebigodes @kylesuss @shilman?

**Comment by jonniebigodes** [comment]
@tmeasday and @stephyswe that is partially addressed, when i did the angular documentation rewording i left in the following in the `get-started` documentation inside a `<div class="aside">`:

> Esta tradução está desatualizada! Ajuda-nos a melhorá-la clicando no link no fim da página. Não somente a equipa agradece, mas toda a comunidade.

Roughly translated to english what is said above is the following: "This translation is not updated! You can help us improve it by clicking the link at the bottom of the page, not only the team will appreciate it but also the entire community"

The same is applied to the spanish version of the said tutorial,

I forgot to create a pull request / create a issue to address this after the changes for the React version went through.

**Comment by domyen** [comment]
Yea, that makes sense to show @tmeasday. We could probably do it as an `.aside` message in Markdown. Good wording @jonniebigodes

**Comment by kylesuss** [comment]
I'm on board w/ the idea. Does seem like it could be hard to remember to add/remove the banner though, especially if it is an all manual process. Anyone have a good idea for that?

**Comment by jonniebigodes** [comment]
@tmeasday @domyen @kylesuss i was thinking about it and the present state of how the documentation is structured. My first thought was to add in a new field by extending the already existing nodes that gatsby will create for the markdown. Something like `lastModified` and possibly use it as a baseline to compare both the original version of the documentation/tutorial with a translation. In paper it sounded good and could probably be done with some effort, but then after some digging it seems that this approach will only work if a contributor or someone willing to make a change to the documentation has the repo cloned locally. Then we could go about it and use a graphql query like the following:
```graphql
markdownRemark(fields: { slug: { eq: $slug } }) {
      
      fields {
        title
      }
      parent {
        ... on File {
          mtime
        }
      }
}
```
Now this would work, but it's when GitHub gets into the mix that things get interesting, as it seems that GitHub doesn't save the modified date for the files, so back to square one... I checked for some headless cms that could address this issue and so far nothing that stands out. Upon a little more "digging around" i stumbled upon [this](https://joshuatz.com/posts/2019/gatsby-better-last-updated-or-modified-dates-for-posts/) in paper it could work and fit into what's intended, i haven't checked this in detail and try to come up with a possible way to use it for this scenario. I've also checked into some Gatsby plugins that could address this, but so far what i've came up across is one that was not updated in more than 8 months and that timeframe in Gatsby terms is a bit too long as Gatsby is constantly being updated and their data layer is constantly evolving and another one that was created by one of Gatsby employees hasn't been changed in more than 18 months...

**Comment by tmeasday** [comment]
Hmm, interesting thought @jonniebigodes.

Honestly I was just thinking we'd have a global "latest storybook minor version" (e.g 5.3) somewhere in our config, and then each translation would have a field saying what version it was translated up to.

Then when you submitted a PR updating a translation for say 6.0, you'd update the local field. You'd pretty quickly realise when the PR was merged if you'd forgotten to do it..?

**Comment by jonniebigodes** [comment]
I left that option as food for thought, something that could be used to automate and streamline the whole processs. Leaving in the hands of the translator to implement the translation. 

But we can do better with less work, with your comment in mind @tmeasday and taking a quick survey of the present state of the documentation these are the results:

```markdown
|              |     English    | German          | Spanish         | Dutch           | Portuguese      | Chinese (Mainland) | Chinese (Taiwan) |
|:------------:|:--------------:|-----------------|-----------------|-----------------|-----------------|--------------------|:----------------:|
|    Angular   | in 5.3 version | N/A             | pre 5.3 version | N/A             | pre 5.3 version | N/A                | N/A              |
|     React    | in 5.3 version | pre 5.3 version | pre 5.3 version | pre 5.3 version | pre 5.3 version | pre 5.3 version    | pre 5.3 version  |
| React Native | in 5.3 version | N/A             | N/A             | N/A             | N/A             | N/A                | N/A              |
|    Svelte    | in 5.3 version | N/A             | N/A             | N/A             | N/A             | N/A                | N/A              |
|      Vue     | in 5.3 version | N/A             | in 5.3          | N/A             | in 5.3 version  | N/A                | N/A              |
```
Also we have something right out of the bat at our disposal that could be used a "source of truth", more specifically for the [Intro to Storybook](https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/index.md) and for the [Design Systems for Developers](https://github.com/chromaui/learnstorybook.com/blob/master/content/design-systems-for-developers/index.md) we could extend the frontmatter by adding a new key called `guideVersion` ( probably a better naming...) with the following:

```javascript
guideVersion:
 [
   {
     framework: 'Angular',
     currentGuideVersion: [
       {
         language: 'en',
         StorybookVersion: 5.3
       },
       {
         language: 'pt',
         StorybookVersion: 5.2
       },
       {
         language: 'es',
         StorybookVersion: 5.1
       }
     ]
   }
 ]
```

Create a new file with a message tailored to the existing languages with the following;
> This guide is updated to Storybook version x.x.x, you can help us improve it by clicking in the link at the bottom of the page. Not only the team  will appreciate it but also the entire community

We replace `x.x.x` with the semantic version fetched from above. This will allow us some "breathing space" not only for future improvements but allow each version/translation some customization.


If you'll allow me...future wise this could be further improved by fetching the `@storybook` version present in the package.json e and use it as a means of comparison. It would mean keeping the version used here constantly updated and would involve some work, but in humble opinion it would bring some benifits, As LSB acts something as the "entry gateway" to the framework. The official docs cover some aspects but if people want to learn they use the tutorials here as a reference.

Feel free to provide feedback.

**Comment by tmeasday** [comment]
> If you'll allow me...future wise this could be further improved by fetching the @storybook version present in the package.json e and use it as a means of comparison

We could definitely do that but probably we can at the least remember to update the global "latest SB version" once in the metadata whenever we do a minor release (we don't need to worry about it when doing patch releases, e.g. 5.3.10).

I think what you are thinking there sounds about right. Thanks for doing the research on the table, very helpful.

**Comment by domyen** [comment]
I'm in favor of simplicity here. Will defer to y'all on this (@tmeasday @jonniebigodes).  Thanks for thinking it through 🙇‍♂️

**Comment by jonniebigodes** [comment]
Closing this as the feature is already in place.
