### ISSUE TITLE
Incorrect import path for src/shared/global.js

### ISSUE THREAD

**Issue by MatthewTFarley** [chromaui/learnstorybook.com#307]
In the [Design Systems for Developers - Test Section](https://www.learnstorybook.com/design-systems-for-developers/react/en/test/), there is an incorrect import path used:

<img width="1203" alt="incorrect-import-path-learn-storybook-com-design-systems-for-developers-test" src="https://user-images.githubusercontent.com/9663417/80312779-47b38880-87b5-11ea-958f-320073c1ace8.png">

The path to this file should be
```js
import { GlobalStyle } from '../src/shared/global';
```
This is incorrect for both English and Portuguese versions.
- https://github.com/chromaui/learnstorybook.com/blame/dbb516e9f6446716d23bc451690bd49f76e36a27/content/design-systems-for-developers/react/en/test.md#L214

- https://github.com/chromaui/learnstorybook.com/blame/dbb516e9f6446716d23bc451690bd49f76e36a27/content/design-systems-for-developers/react/pt/test.md#L207

**Comment by MatthewTFarley** [comment]
#308 has the fix for this.

**Comment by jonniebigodes** [comment]
@MatthewTFarley thanks for the contribution. I'm gonna check on my end and notes but if memory serves me right i think that you're correct and the import is incorrect. Do you mind waiting a bit while i check this?

**Comment by MatthewTFarley** [comment]
@jonniebigodes, not a problem.

**Comment by domyen** [comment]
Thank you @MatthewTFarley! 🙏

**Comment by jonniebigodes** [comment]
@domyen yep this is correct. I can scratch this one from my notes.

Closing this with #308
