### ISSUE TITLE
Noob question: how to use components created in Storybook

### ISSUE THREAD

**Issue by theWebalyst** [chromaui/learnstorybook.com#315]
I've created a local storybook `svelte-iux` for svelte component development but in the tutorials I can't find an explanation of how to use these (example) components in a project. I've tried `yarn build` and then yarn linking from my project to the `svelte-iux` storybook I've created, but my project doesn't resolve `svelte-iux`.

In my project I have:
```
import {button} from 'svelte-iux';
```
But I'm getting a build error:
```
ERROR in ./src/App.svelte
Module not found: Error: Can't resolve './svelte-iux' in '/home/djh/visualisation/visualisation-lab/src'
 @ ./src/App.svelte 24:0-38
 @ ./src/main.js
 @ multi ./src/main.js
```
What am I missing?! Thanks.

PS I should add that I have the storybook IDE all working on localhost, it is how to use these components in a project I am not understanding.

**Comment by jonniebigodes** [comment]
@theWebalyst sorry for issue you're facing. From your description it seems that what you want to achieve falls under [design systems for developers](https://www.learnstorybook.com/design-systems-for-developers/) guide.  The intro to Storybook only gives you the "tools" needed for start implementing your storybook in a application. To use the components and probably the storybook you've setup you'll need to make the `svelte-iux` into a component library which would be then consumed in a client app. Something like described [here](https://medium.com/@maoznir/creating-a-svelte-components-library-b2134884735f), you'll probably need to adjust to your use case, but it seems that's the way to go.

Also from a personal point of view, this is not a "noob" question, but a perfect valid one and glad that you asked as this could offer some insights for other developers aswell.

Feel free to provide feedback

**Comment by theWebalyst** [comment]
Thanks @jonniebigodes that's very helpful, and great to have such a quick response.
