### ISSUE TITLE
Broken Link to Framework React Native : Testing

### ISSUE THREAD

**Issue by Darth-Knoppix** [chromaui/learnstorybook.com#320]
### Problem:

From https://www.learnstorybook.com/intro-to-storybook/react/en/test/, navigating to the React Native link renders a blank page. This is because the link is broken.

![Screenshot 2020-06-01 at 14 34 35](https://user-images.githubusercontent.com/2019236/83414305-2c234980-a415-11ea-9f4d-e940e3ef57f9.png)

Notice the URL is a serialised `[object Object]`.

![Screenshot 2020-06-01 at 14 34 26](https://user-images.githubusercontent.com/2019236/83414302-2af21c80-a415-11ea-9608-3ea72d029fd4.png)

May be related to [FrameworkMenu#getChapterInOtherLanguage](https://github.com/chromaui/learnstorybook.com/blob/a3d12324719807bc676e8f85b7d0b4a357b890a5/src/components/screens/ChapterScreen/LanguageMenu/FrameworkMenu.js#L75) because React Native doesn't have a matching translation (there is no corresponding  **en/test.md**)

**Comment by jonniebigodes** [comment]
@Darth-Knoppix first and foremost sorry for the inconvenience that presented itself with this issue. And second thank you very much for bringing this to the attention. I'm going to take a look at it and possibly fix it in a timely fashion. 

Do you mind waiting a bit while this is triaged? 

Stay safe.

**Comment by Darth-Knoppix** [comment]
Not an inconvenience at all, just wanted to let you know so it’s known and can be fixed. 👍
