### ISSUE TITLE
Bad TaskModule import in intro-to-storybook/angular[en|pt]/screen

### ISSUE THREAD

**Issue by julien-deramond** [chromaui/learnstorybook.com#322]
In https://www.learnstorybook.com/intro-to-storybook/angular/en/screen/, we can see 

```
//src/app/app.module.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { TaskModule } from './tasks/task.module';
import { NgxsModule } from '@ngxs/store';
import { NgxsReduxDevtoolsPluginModule } from '@ngxs/devtools-plugin';
import { NgxsLoggerPluginModule } from '@ngxs/logger-plugin';
import { AppComponent } from './app.component';
import { InboxScreenComponent } from './components/inbox-screen.component';
import { PureInboxScreenComponent } from './components/pure-inbox-screen.component';

@NgModule({
  declarations: [AppComponent, InboxScreenComponent, PureInboxScreenComponent],
  imports: [
    BrowserModule,
    TaskModule,
    NgxsModule.forRoot([]),
    NgxsReduxDevtoolsPluginModule.forRoot(),
    NgxsLoggerPluginModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

There is a problem with the `TaskModule` import which should be 

```
import { TaskModule } from './components/task.module';
```

The same thing is happening here https://www.learnstorybook.com/intro-to-storybook/angular/pt/screen/.

**Proof:** The previous page in the tutorial already mentions this import (source: https://www.learnstorybook.com/intro-to-storybook/angular/en/data/).

**Note:** This problem does not seem to happen in Spanish because the documentation is different (the steps are different).

If I'm not mistaken, I don't have the permissions to push a branch in order to create a PR. Here is the fix I thought about:

```diff
diff --git a/content/intro-to-storybook/angular/en/screen.md b/content/intro-to-storybook/angular/en/screen.md
index 0f5b952..b8e75bc 100644
--- a/content/intro-to-storybook/angular/en/screen.md
+++ b/content/intro-to-storybook/angular/en/screen.md
@@ -209,7 +209,7 @@ And finally the `app.module.ts`:

 import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
-import { TaskModule } from './tasks/task.module';
+import { TaskModule } from './components/task.module';
 import { NgxsModule } from '@ngxs/store';
 import { NgxsReduxDevtoolsPluginModule } from '@ngxs/devtools-plugin';
 import { NgxsLoggerPluginModule } from '@ngxs/logger-plugin';
diff --git a/content/intro-to-storybook/angular/pt/screen.md b/content/intro-to-storybook/angular/pt/screen.md
index 124ccfe..70457ac 100644
--- a/content/intro-to-storybook/angular/pt/screen.md
+++ b/content/intro-to-storybook/angular/pt/screen.md
@@ -209,7 +209,7 @@ E com isto uma última alteração, esta no ficheiro (ou arquivo) `app.module.ts

 import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
-import { TaskModule } from './tasks/task.module';
+import { TaskModule } from './components/task.module';
 import { NgxsModule } from '@ngxs/store';
 import { NgxsReduxDevtoolsPluginModule } from '@ngxs/devtools-plugin';
 import { NgxsLoggerPluginModule } from '@ngxs/logger-plugin';
```

**Comment by jonniebigodes** [comment]
@julien-deramond i'm going to check out on my end as i was the person behind the rework on said documentation. And if it checks out it might be that i might have forgotten to copy the correct code snippet and for that i'm trully sorry for the inconvenience that it caused and trully grateful that you spotted it. A pr will be up soon.

**Comment by jonniebigodes** [comment]
@julien-deramond i've confirmed and you're right, in the repo that was used to back the documentation during the rework of said documentation the import is equal to the one you mentioned, but in the actual documentation it's still using the old imports that were in effect. As you can see [here](https://github.com/jonniebigodes/intro-storybook-5_3-angular/blob/master/src/app/app.module.ts#L20), once again sorry for the inconvenience that this mishap has caused.

**Comment by julien-deramond** [comment]
No problem, there was no inconvenience.
Thank you @jonniebigodes for the PR.
