### ISSUE TITLE
Confusing and unusable Build UI components tutorial 

### ISSUE THREAD

**Issue by valk** [chromaui/learnstorybook.com#349]
If you're following [Build UI components](https://www.learnstorybook.com/design-systems-for-developers/react/en/build/) you won't be able to see the results described within it since files are missing, for example `styles` css.

Also `styled-components` is missing.

**Comment by jonniebigodes** [comment]
@valk thank you bringing this to our attention. This tutorial was recently reworked and probably it's going to be subject to another update probably soon. I'll take this to the authors attention and when the update comes we want to make sure that the issue you're experiencing is factored in.

If you don't mind waiting a bit longer while me and the remainder elements of the team work on it and we'll get back to you.

Sounds good?

Stay safe

**Comment by jonniebigodes** [comment]
Going to close the issue, with #380 the tutorial was updated to 6.0 and some other changes introduced. Take a look at it and re-open if this still persists.

Stay safe.
