### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by jonniebigodes** [chromaui/learnstorybook.com#350]
This issue addresses the recent changes introduced to the Intro to Storybook tutorial. As of now the translations will need a bit of work.

I'll work on updating the portuguese translations shortly, so that they match the current versions.

Also i would like to ask:
- @IvanSotelo if you're able and have the time, can you take care of the spanish translations? This based on the fact that you've been doing a fantastic job getting the tutorial translate to Spanish. Me personally and i believe the rest of the team is also more than thankfull for the effort you made.

- @renet if you're able and have the time, we could use your help updating the German translation of the tutorial, as of a recent check there's some rework to do. 
- @Robin-Hoodie i ask you the same question as i did to the other contributors. If you have the time to update the translation you made it would be fantastic.

Feel free to provide feedback.

Hope you all are doing good during these times.

Stay safe

**Comment by Robin-Hoodie** [comment]
@jonniebigodes Depending on the size of the translations, I can do that. Do you have an esimate as to how much will have to be translated?

**Comment by jonniebigodes** [comment]
@Robin-Hoodie thank you for checking in.

Regarding the translation, what needs to be done. So far you'll just need make some changes in the following sections:
- Deploy
- Testing
- Create a addon just needs a minor change.

It's not a big change.

If you take a look at those sections in the english version and compare them to yours you'll see the differences.

Stay safe

**Comment by IvanSotelo** [comment]
@jonniebigodes Sure, I'll work on it this weekend.

Best

**Comment by jonniebigodes** [comment]
@IvanSotelo thank you for taking a look aswell. Hope you're doing good :)
