### ISSUE TITLE
Archived Task Checkbox Behaviour (React Intro to Storybook tutorial) 

### ISSUE THREAD

**Issue by yNaxon** [chromaui/learnstorybook.com#351]
When you get to the [Addons](https://www.learnstorybook.com/intro-to-storybook/react/en/using-addons/) chapter in the React Intro to Storybook tutorial, you add knobs to manipulate Task props.
As can be seen in the [demonstration video](https://www.learnstorybook.com/intro-to-storybook/addon-knobs-demo.mp4), the checkbox should be checked when the `state` prop value is set to `TASK_ARCHIVED`.

In reality however, the checkbox is not checked - because it's uncontrolled:

```
// src/components/Task.js

export default function Task({ task: { id, title, state }, onArchiveTask, onPinTask }) {
  return (
    // ...
    <input
        type="checkbox"
        defaultChecked={state === 'TASK_ARCHIVED'}
        disabled={true}
        name="checked"
    />
    // ...
  )
}
```

![Screen Recording 2020-08-04 at 12 45 26](https://user-images.githubusercontent.com/20519899/89280078-cb9ccc80-d650-11ea-9f6a-3c6622601d4d.gif)

If we want the checkbox to behave same as in the demonstration video - check or uncheck based on the `state` prop value, it should be controlled:
```
// src/components/Task.js

export default function Task({ task: { id, title, state }, onArchiveTask, onPinTask }) {
  return (
    // ...
    <input
        type="checkbox"
        checked={state === 'TASK_ARCHIVED'}
        disabled={true}
        name="checked"
    />
    // ...
  )
}
```

**Comment by jonniebigodes** [comment]
@yNaxon thank you for bringing this to our attention. 

I'm not the author of the documentation, but based on my experience with the tutorial and the implementation behind it, the author went with a simple approach, trying to keep the reader engaged on how add and use the addon. 

The tutorial is going to take a bit of a rework in the near future, with that i'll take this issue to the team and see what is the best approach here.

Stay safe

**Comment by jonniebigodes** [comment]
Going to close this issue as with 6.0 the behavior is now not being displayed. Feel free to re-open the issue if you encounter the issue.

Stay safe
