### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by pavelkeyzik** [chromaui/learnstorybook.com#371]
Hey guys! What about support Cyrillic? 

## The problem
At this moment we're using font `Nunito Sans` but the problem is that this font doesn't support Cyrillic and we're not able to add translation in Russian.

## Solution
I found that Google has another font called `Nunito` and it looks the same (attachment below). As you may see that font is pretty much the same as `Nunito Sans`. The only difference between that fonts is that letter spacing between `W` and `h` is bigger. Maybe you'll find somewhere another issue with that font but I hope it'll help us to write new translations. 

![image](https://user-images.githubusercontent.com/17102399/91601044-a78f8b00-e971-11ea-96f7-2d02bcaa477a.png)

Let me know what you think about this update?

**Comment by jonniebigodes** [comment]
@pavelkeyzik let me check something and come back to you. At first glance it shouldn't  be a issue and we could probably use Nunito instead of Nunito Sans. I'll let you know once i get more on this.

Do you mind waiting a bit? 

Stay safe

**Comment by pavelkeyzik** [comment]
@jonniebigodes Sounds great 😊

**Comment by domyen** [comment]
Thanks @pavelkeyzik, we haven't considered Cyrillic because no one has volunteered a Russian translation yet (maybe you?).

Nunito and Nunito Sans are different fonts. Nunito has rounded smooth characters while Nunito Sans doesn't. If we did end up with a Russian translation, we can explore swapping out the font for that specific translation to a different system font that supports Cyrillic.

**Comment by pavelkeyzik** [comment]
@domyen Yeah, I realized that your project doesn't have Russian translation and thought that I can try to help with it in the future.

**Comment by domyen** [comment]
Awesome Pavel, we'd love a Russian translation!

Once that's started, we'll figure out how to support Cyrillic (will need to
update the implementation).

**Comment by jonniebigodes** [comment]
@pavelkeyzik just a friendly reminder. Are you able to work on a Russian translation? We'd love to get one featured in the documentation. Let us know so that we can adjust accordingly.

Stay safe

**Comment by pavelkeyzik** [comment]
@jonathanherdt Sorry, but at the moment I don't have enough time to work on this issue 😢

**Comment by jonniebigodes** [comment]
@pavelkeyzik no worries, i'll leave it open for the time being. Let me know once you got something and we'll go from there.

Stay safe

**Comment by jonniebigodes** [comment]
@pavelkeyzik closing the issue. If you're still interested in working on it and providing a Cyrillic translation let me know and I'll open this and follow up with you!

Have a great week!

Stay safe

**Comment by pavelkeyzik** [comment]
Thank you @jonniebigodes! Have a great week too 👋
