### ISSUE TITLE
Svelte - default export mentions component, but not actually in the code

### ISSUE THREAD

**Issue by jdhines** [chromaui/learnstorybook.com#375]
This is pretty small, but I'm just getting in to Storybook for the first time, so didn't want to just do a PR in case I'm misunderstanding something (but I'd be happy to once I do!)

On the [Svelte Simple Component](https://www.learnstorybook.com/intro-to-storybook/svelte/en/simple-component/) page it says:

> To tell Storybook about the component we are documenting, we create a default export that contains:
>    * component -- the component itself,
>    * title -- how to refer to the component in the sidebar of the Storybook app,
>    * excludeStories -- information required by the story, but should not be rendered by the Storybook app.

However, the code given doesn't have a `component`:

```javascript
export default {
  title: 'Task',
  excludeStories: /.*Data$/,
}
```

Should that "component" bullet be removed, or is the example code missing it from the default export?

**Comment by jonniebigodes** [comment]
@jdhines i was the author of the that version of the tutorial. And upon checking it, it seems that you're correct. The bullet item regarding the default export is actually introducing a misleading. As the component key is used in the story itself. I'm ok with a small pull request removing it the bullet. Or if you are interested we would greatly appreciate if you would be willing to update this version of the tutorial to the new Storybook version. We recently updated the [react version](https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/) but some of the other frameworks are still not up to par. 

Let me know if you're willing and we can coordinate better.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this issue as wit the merge of #432 this is now solved
