### ISSUE TITLE
Intro to Storybook code base updates

### ISSUE THREAD

**Issue by jonniebigodes** [chromaui/learnstorybook.com#386]
With the release of Storybook 6.0 some changes were introduced. I've updating them to the best of my knowledge, but it could be that some mistakes might have been introduced, or some best practices for any framework, might have been overlooked. With that i would like to reach out and ask the community for some help with providing the most accurate code examples in the tutorial.

As of present state of the tutorial the following frameworks are updated:

| Framework     | Guide version  |Contributor.      |
|:--------------|:---------------|:---------------|
|React                | 6.2                   |                           |
|Vue                  | 6.2                    |@andre-brdoch |
|Angular            | 6.2                    |                           |
|Svelte              | 6.2                    |                           |
|React Native   | 5.3                    |                           |
|Ember             |  6.2                    |@gossi               |              

I would like to point out that version 3 of Vue was just released and the rest of the team of maintainers are working to get support for it in a future release, probably 6.1, but probably not, it will depend on their workload. For the time being it would be best if the code used would target version 2 of Vue as based on some research it's working correctly.

React Native is also another case that needs a bit of attention as it's actively being updated by some community members and i'm coordinating with them to offer a better experience for the readers, for now it's better to leave it as is until we get a more accurate implementation and solve some issues that are still lingering.

If willing to help, i would only ask that asides from updating the snippets in the tutorial, include a repo to match the documentation so that it can better looked at.

Also add me as a reviewer in the pull request or ping me in the [Storybook discord](https://discord.gg/UUt2PJb)

Thanks in advance for any help in tackling this issue.

Stay safe all of you

**Comment by andre-brdoch** [comment]
Hey Jonnie,

I'd be happy to help out with the Vue snippets. However, there are still a few features like composite components that I did not yet get to work with vue, so any help there would be very much appreciated! 

I could get started with the snippets / test repo in the next few days.

**Comment by jonniebigodes** [comment]
@andre-brdoch thank you very much for the answer and the willingness to help with Vue. Let me know when you have a repo setup and i'll clone it and we can coordinate from there. You can ping me in the [Storybook Discord Server](https://discord.gg/UUt2PJb) (the same username).

**Comment by usrrname** [comment]
I'd be happy to help with the Angular one. Spent the last 2 weeks worming through a lot of old and new versions to try and get my own demo working 😆

**Comment by argarner** [comment]
I just completed the Angular tutorial, which I believe was updated to use degit earlier this year, and I would suggest re-doing all the "Keep your code in sync with this chapter. View <commit> on Github" commits referenced in [this repo](https://github.com/chromaui/learnstorybook-code), as the demo test code throughout (now using '@testing-library/angular') is very different from the "sync" code of each commit (e.g. See the "Composite component" `task-list.component.spec.ts` file [in this commit](https://github.com/chromaui/learnstorybook-code/commit/d3abd86) vs the code [in my commit](https://github.com/argarner/storybook-taskbox/commit/1fbcc6e7a26df38a7f5013c57e56735a2983a4cb)

**Comment by jonniebigodes** [comment]
@argarner I'm well aware of the issue, I'm still working on code updates based on the Storybook 6.3 release for all the tutorials. This requires a bit of work and some polishing up.

Thanks for letting us know about that package. Something that we could probably take a look at and possibly implement it .

**Comment by jonniebigodes** [comment]
Closing this issue as the framework versions for all the tutorials are already updated!
