### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by kylemh** [chromaui/learnstorybook.com#39]
### ENV
- MacBook Pro 2017
- MacOS High Sierra v10.13.5
- Node v8.9.4
- Yarn v1.7.0

### STR
- Fork repository
- Clone repository locally
- Open a shell within the folder's root level
- Run `yarn && yarn dev`
- Open http://localhost:8000
- See the following error:
![screen shot 2018-07-11 at 11 39 16 pm](https://user-images.githubusercontent.com/9523719/42616721-175117ca-8564-11e8-88db-d23b26abc1ee.png)

I thought this might be because the `yarn.lock` file has not been updated in parity with the `package-lock.json` file; however, after deleting it locally and adding a fresh lockfile, the error persisted. There also exists a lint error on line 66 of `src/pages/index.js`, but fixing this also does not resolve the screenshotted issue. I'll be submitting a PR soon in regards to #21 but I'll just keep it to content 👍

**Comment by tmeasday** [comment]
Thanks @kylemh. This was an issue that Gatsby obscured because we had a commit that was purely numeric. I guess it confused the auto-GraphQL schema generation?

PS `package-lock.json` should not have been there. Removing it.
