### ISSUE TITLE
Change references to `master` to `main` to reflect GitHub's new default branch name

### ISSUE THREAD

**Issue by itsojon** [chromaui/learnstorybook.com#408]
As described [here](https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name), new GitHub repos now have a default branch named `main` instead of `master`.

- [x] Update English design systems guide (https://github.com/chromaui/learnstorybook.com/pull/402)
- [ ] Update Portuguese design systems guide
- [ ] Update code in https://github.com/chromaui/learnstorybook-design-system, like [this code](https://github.com/chromaui/learnstorybook-design-system/blob/2d0450a27643675ecd93b3d18656705c703c8bca/.github/workflows/push.yml#L7)
- [ ] Update the other guides

**Comment by jonniebigodes** [comment]
@itsojon thanks for the issue and the help on keeping track of the progress. Really appreciate it. One item that need some attention is the "Update code in https://github.com/chromaui/learnstorybook-design-system....". I'll ask the maintainers on how we should proceed on this and i'll get back to you. Sounds good?

Stay safe

**Comment by jonniebigodes** [comment]
@itsojon i've just pushed a pull request to address the Intro to Storybook tutorial. All versions (minus the Vue/en) are updated accordingly to reflect the changes. I'm going to merge it shortly. So we can add another check mark in the issue. Sounds good?

**Comment by itsojon** [comment]
@jonniebigodes sounds good! Thank you!

**Comment by jonniebigodes** [comment]
Closing this for now. As the the tutorials are being updated the references will also be updated.
