### ISSUE TITLE
Eng-Ko translation needed in Get-Started page

### ISSUE THREAD

**Issue by ghost** [chromaui/learnstorybook.com#415]
@sosunnyproject 
Hi, first of all, I appreciate your work for eng-ko translation. It was so much helpful studying storybook.

While I was studying storybook in English, I realized Korean translation is provided.
Then, I found out this part below in "Get Started" page is missing Korean translation.
"With a recent update to React and CRA you'll need to downgrade react-scripts package to a previous version in order to run Storybook without any issues, version 3.4.3 will work perfectly. Also both the React and ReactDOM will require a downgrade to a previous version. Version 16.14.0 of both packages will work perfectly.
See the Yarn official documentation on how to add and remove packages."

So I was wondering if you and other collaborators can work on this one as well 🙂

**Comment by jonniebigodes** [comment]
@JimmyJoo this is an issue we're aware of. The Intro to Storybook tutorial is currently being updated to address some issues with React 17/ Create React App 4.0.0 recent release. Once the documentation is updated i'm going to ask the translators to adjust accordingly based on the updates introduced. Sorry for any inconvenience introduced.

Stay safe

**Comment by jonniebigodes** [comment]
@JimmyJoo i've merged an update to the tutorial that addresses that issue. If you're ok, we'd love an update to the Korean translation based on the recent changes. Let me know when you have a pull request up and we'll go from there. Sounds good?

Stay safe
