### ISSUE TITLE
plan of translate chinese 🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [chromaui/learnstorybook.com#42]
## or I just pull

**Comment by domyen** [comment]
Awesome! Thanks @chinanf-boy! Submit a PR and we'll discuss it there.

**Comment by chinanf-boy** [comment]
Right -> #43

**Comment by domyen** [comment]
Let's chat in the PR. Closing this issue out ✅

**Comment by Mingyang-Li** [comment]
Am I too late for the translation party? @chinanf-boy - 需要翻译的部分尽管跟我说

**Comment by jonniebigodes** [comment]
@Mingyang-Li no, you're not. We're stoked that you're interested in translating the tutorials as currently, they're outdated and in need of some updates. If you could leave a comment in the issue addressing translations (#3) expressing your interest in working on the translations and which tutorial you want to start with, I'd appreciate it.
