### ISSUE TITLE
Testing Connected Components

### ISSUE THREAD

**Issue by developer239** [chromaui/learnstorybook.com#421]
Can we please remove this guide and jus write in few simple sentences that in reality we:

- can't test connected components
- we have to extract the UI and then test our extracted pure components

This tutorial is misleading and not helpful at all.

**edit:** When I thought about it it probably doesn't make sense to test connected components. Maybe we should clearly tell all users that the Storybook is not intended for that use case and that is the reason why we need to extract the UI into separate components. 

Writing a tutorial this long and pretending that we can test connected components even though we don't actually test connected components is quite toxic in my opinion.

https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/angular/en/data.md

**Comment by developer239** [comment]
@jonniebigodes I will post what I have by the end of the weekend. Maybe it will help. 🙌

**Comment by jonniebigodes** [comment]
@developer239 sure. Looking forward for it. Help is always welcome.

**Comment by jonniebigodes** [comment]
Closing this now @developer239 ! If you're ok with following up with this issue, let me know and we'll go from there!

Have a great week!

Stay safe

**Comment by developer239** [comment]
@jonniebigodes Sorry about that. I started playing with C++ where things don't work but because I don't understand why they don't work I don't find it as frustrating as javascript. 😀

**Comment by jonniebigodes** [comment]
@developer239 nothing to be sorry about, don't worry about it! Hope you're having fun with C++ and learning as much as you can! If you ever decide to come back to this "side of the border" (pardon the bad pun) and you're willing to take another pass at this, I'll be more than glad to follow up with you on this.

**Comment by developer239** [comment]
@jonniebigodes I will get back to this issue when I am working on a production project that has redux and storybook. I have a pretty good idea of what I want to do.
