### ISSUE TITLE
Problem with tutoria Intro to Storybook for React

### ISSUE THREAD

**Issue by Magicianred** [chromaui/learnstorybook.com#426]
I am follow the tutorial 
https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/

and I had to fix more things in order to have all the 3 frontend running (in addition to the fixes already present on tutorial)

1. I have to install babel-loader in version 8.1.0
2. I have to add import React in the files:
  - taskbox/src/App.js
  - taskbox/src/App.test.js

thanks

**Comment by jonniebigodes** [comment]
@Magicianred this is known issue that the Storybook maintainers and the community have been working on. With the release of CRA 4 and React 17 some problems were introduced. Most of them are solved as of this point. But the babel clash between the one used by CRA and the one used by Storybook is still being worked on. From the tutorial's point of view code and content wise you should only need to add the `.env` file with the `SKIP_PREFLIGHT_CHECK=true`. 

Including this small change will allow you to run all 3 environments. I've been working on this and i'm going to push an update sometime next week. I just need to polish some items. 

Stay safe

**Comment by jonniebigodes** [comment]
@Magicianred going to close this as i've just merged an update for the tutorial that addresses this situation with a workaround to get you unblocked while following the tutorial. 

Stay safe
