### ISSUE TITLE
Missing instruction to enter real Chromatic token in yml file

### ISSUE THREAD

**Issue by TamaraPK** [chromaui/learnstorybook.com#439]
Location: [here](https://www.learnstorybook.com/design-systems-for-developers/react/en/review/)

The page forgets to mention that in the yaml file one needs to replace project token with the actual token from Chromatic. It only states the below:
"Create a file called chromatic.yml like the one below. This will allow us to script how our CI process behaves. We'll start small for now and continue to improve it as we progress:"

One may just copy and paste the yml content and wonder what went wrong :)

**Comment by jonniebigodes** [comment]
@TamaraPK Closing the issue now as the tutorial was updated in #461 with adjustments to the documentation in that particular section. Thank you for bringing this to our attention. Let us know if you run into any other issues with the tutorials.

Stay safe

**Comment by TamaraPK** [comment]
Thank you! Have a great weekend!

**Comment by jonniebigodes** [comment]
No need to thank, I'm the one that should be thanking you for bringing this to our attention. Have a great weekend as well.

Stay safe
