### ISSUE TITLE
Disjointed reference

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#447]
Intro to SB bug reported by reader:

In chapter 2 we reference CSS from chapter 1:
![image](https://user-images.githubusercontent.com/263385/108629805-a5454f80-742f-11eb-9887-25e4f88cf980.png)

But we no longer need this because the entire repo is cloneable with degit (css included)

**Comment by jonniebigodes** [comment]
Closing this as it's already addressed
