### ISSUE TITLE
Snapshot Testing fails in Intro to Storybook for Angular in 'Simple Component' Step.

### ISSUE THREAD

**Issue by ORIGINALUSRNM** [chromaui/learnstorybook.com#476]
When following the [Intro To Storybook tutorial for Angular,](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/simple-component/) the Snapshot Testing step fails when running `npm run test` with the error: 'Cannot find module '@storybook/angular/renderer' from 'node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/renderTree.js'.   See console error below

Platform: macOS Catalina 10.15.5
Node: v14.15.1
NPM: v6.14.8

Console Error: 

`  ● Test suite failed to run

    Cannot find module '@storybook/angular/renderer' from 'node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/renderTree.js'

    Require stack:
      node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/renderTree.js
      node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/loader.js
      node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js
      node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js
      node_modules/@storybook/addon-storyshots/dist/ts3.9/index.js
      src/storybook.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/angular/renderTree.js:29:18)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.453 s
Ran all test `suites.``

**Comment by ORIGINALUSRNM** [comment]
Also fails with same error with Node v14.16.1 and NPM 6.14.12

**Comment by jonniebigodes** [comment]
@ORIGINALUSRNM thank you for bringing this to our attention. I've been working on some updates for that particular version of the tutorial and with that, I factored in your issue. Upon checking it seems that it might be related to a mismatch of versions. I'm currently reviewing #482 for any missing information related to the tutorial. Also, the template for the tutorial is currently being updated to 6.2 as well. Once the pull request I've mentioned is merged, I would like for you to go through it and see if the problem still persists and let me know.

As a side note, the changes to the template and the code i applied for the tutorial are based on that particular version of node/npm.

Stay safe

**Comment by jonniebigodes** [comment]
@ORIGINALUSRNM going to close this. I've run this with the current version Storybook version featured in the tutorial and now with the release of 6.3 and wasn't able to reproduce the issue. If interested I'll gladly push my updated version of the tutorial to a repository and you can take a look at it.

Stay safe
