### ISSUE TITLE
Provide a better path to the framework specific tutorials (other than react)

### ISSUE THREAD

**Issue by etsiaDigital** [chromaui/learnstorybook.com#484]
The "Get Started" button on this page: https://storybook.js.org/tutorials/intro-to-storybook/ is hard coded to "react".
There should be some way to choose your desired framework so that when you "Get Started", you end up at the proper tutorial. Currently you might think that React is the chosen one for "the tutorial"....  (wouldn't be the first time)

A drop down from the button or select beside the button (with default to react) would take care of this.

Currently you have to presume there might be a framework specific tutorial for your desired framework and manually try altering the route.

**Comment by 1aishwaryasharma** [comment]
Even though the default selection is React we can select the framework from the side nav controls.
![Screen Shot 2021-05-09 at 11 32 11 PM](https://user-images.githubusercontent.com/4868615/117602587-0d4a2e80-b11f-11eb-98d5-b034842262c5.png)

**Comment by etsiaDigital** [comment]
Here is the tutorial landing page.  ??  no nav.  There IS a BIG  Get started button.  That takes you to React.  

![storybook_tutorial_page](https://user-images.githubusercontent.com/56901847/117645854-ae9da880-b150-11eb-9f23-b467be97dca6.jpg)

**Comment by jonniebigodes** [comment]
Closing this down, believe that 1aishwaryasharma pretty much answered the question. 

Stay safe both of you
