### ISSUE TITLE
Intro to Storybook Vue Tutorial Broken

### ISSUE THREAD

**Issue by davidshq** [chromaui/learnstorybook.com#494]
Hi All,

I attempted to follow the instructions for the Vue Tutorial:
https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/

I ran into a number of errors when attempting to run `yarn storybook` which appear to be related to `vue-template-compiler` and `vue-loader`.

I was able to get Storybook to load by using @F0rsaken's instructions in https://github.com/storybookjs/storybook/issues/10654#issuecomment-796593903

Specifically, running `yarn add vue-loader@next`

**Comment by jonniebigodes** [comment]
@davidshq thanks for bringing this to our attention. I briefly encountered this issue when updating the documentation (tutorial) to Vue 3. What solved it for me was to clean out my yarn cache and pull in the template and go through the tutorial. I'll check it out once again to see if the issue persists. If that's the case, then I'll adjust the template accordingly and I'll let you know and we'll go from there. Sounds good?

Stay safe

**Comment by BergFulton** [comment]
Having this same exact problem, except in an act of YOLO, I did `npm i` which fixed it and let me restart Storybook during the Composite Components section.

**Comment by MariuszDabrowski** [comment]
I ran into this same issue today, for anyone that stumbles across this, this is the error you get:

<img width="1072" alt="Screen Shot 2021-06-04 at 1 52 08 PM" src="https://user-images.githubusercontent.com/4285139/120843702-6b124080-c53c-11eb-9f0b-46f04a73de6c.png">

Which can be fixed by installing `Vue Loader` by running `yarn add vue-loader@next --dev`

**Comment by jonniebigodes** [comment]
@MariuszDabrowski and @davidshq going to close this down as the issue has resolved itself with Storybook 6.3. I've just finished a rundown on the tutorial with the updated version and no longer the issue presented itself. Can you check on your end and report back if the issue still presents itself and I'll gladly re-open this issue and triage it.

Stay safe both of you

**Comment by prathamesh-gharat** [comment]
I ran into the same issue.

Error: `Error: Cannot find module 'vue/dist/vue.esm-bundler.js'`

My observations.
`\Storybook-inst\node_modules\@storybook\vue3\dist\cjs\server\framework-preset-vue3.js` references `vue/dist/vue.esm-bundler.js` in a line `vue$: require.resolve('vue/dist/vue.esm-bundler.js')`

But `\Storybook-inst\node_modules\vue` is missing. i.e. `vue` package is missing.

`npm i -D vue@latest` and then `npm run storybook` works for me at least.

**Comment by jonniebigodes** [comment]
@prathamesh-gharat no problem whatsoever :)
