### ISSUE TITLE
Instructions to add code, but code is already in the template

### ISSUE THREAD

**Issue by MichaelArestad** [chromaui/learnstorybook.com#505]
On the Document, Distribute, and Workflow chapters, there were a handful of instructions to add documentation or some code as I was following along. What I found was that the documentation or code was already in my clone of the repository. I followed the instructions in the [Architecture](https://storybook.js.org/tutorials/design-systems-for-developers/react/en/architecture/) chapter to clone the files and set up the project locally.

If this is intentional, I would recommend changing the instructions to be clear that no code needs to be added. If it is not, I would recommend removing the relevant code and documentation from the `learnstorybook-design-system-template`.

## [Document](https://storybook.js.org/tutorials/design-systems-for-developers/react/en/document/)

The documentation was already in my clone of the repository. Unfortunately, I didn't take very good notes here and I don't remember specifically which parts of the documentation.

## [Distribute](https://storybook.js.org/tutorials/design-systems-for-developers/react/en/distribute/)

> [Then, let’s create a src/index.js file to create a common entry point for using our design system. From this file we’ll export all our design tokens and the components:](https://github.com/chromaui/learnstorybook.com/blame/master/content/design-systems-for-developers/react/en/distribute.md#L44)

`src/index.js` was already created with the code added.

## [Workflow](https://storybook.js.org/tutorials/design-systems-for-developers/react/en/workflow/)

> [Given that it’s a list, it should show many avatars. Let’s add stories that showcase what happens with numerous list items and what happens with few list items.](https://github.com/chromaui/learnstorybook.com/blame/master/content/design-systems-for-developers/react/en/workflow.md#L52)

`src/AvatarList.stories.js` already had the proposed code.

> [Thanks to Storybook Docs, we get customizable documentation with minimal effort. This helps others learn how to use AvatarList by referring to the Docs tab in Storybook.](https://github.com/chromaui/learnstorybook.com/blame/master/content/design-systems-for-developers/react/en/workflow.md#L99)

I believe much of the documentation here was already added.

**Comment by jonniebigodes** [comment]
@MichaelArestad going about it in order:
- Document
   I've checked the chapter against the template and it's an oversight. The JSDocs comments should not be there. If you're ok with opening up a pr I'll gladly look at it and merge it. 
- Distribute
   I'll test it and if it doesn't break anything we can probably drop it.
- Workflow
   This comes from [this](https://github.com/chromaui/learnstorybook-design-system/pull/21). We can probably close the pr and open a new one and update the file links? 


Thanks for the feedback on this and your help in improving it.

**Comment by MichaelArestad** [comment]
🥳
