### ISSUE TITLE
Missing babel key in package.json

### ISSUE THREAD

**Issue by MichaelArestad** [chromaui/learnstorybook.com#507]
I stumbled a bit in adding a babel key following these instructions:

> [With our build process implemented. We'll need to fine tune it. Locate the babel key in your package.json and update it to the following:](https://github.com/chromaui/learnstorybook.com/blame/master/content/design-systems-for-developers/react/en/distribute.md#L81)

I ended up having to do a bit of searching to work out adding a babel key to `[package.json](https://github.com/chromaui/learnstorybook-design-system-template/blob/master/package.json)`.

It might be good to either clarify the language when to add the babel key or to add the key to `[package.json](https://github.com/chromaui/learnstorybook-design-system-template/blob/master/package.json)`.

**Comment by jonniebigodes** [comment]
@MichaelArestad feel free to push it to a pr in the template. I'll check it out and if it doesn't break anything I'll merge it. Leaves one less concern to the readers. WDYT?

Let me know once the pull request is up.

**Comment by MichaelArestad** [comment]
@jonniebigodes I'll have to crack open my personal computer to check out what I did. I'm also _far_ from an expert in composing `package.json`. I likely won't get to this until my next empathy day, though.
