### ISSUE TITLE
Icon font error

### ISSUE THREAD

**Issue by janicak** [chromaui/learnstorybook.com#52]
Following instructions through https://www.learnstorybook.com/react/en/simple-component/, the icon font fails to load in the application, with console warnings:

```
iframe.html?selectedKind=Task&selectedStory=archived:1 Failed to decode downloaded font: http://localhost:9009/icon/percolate.woff?5w3um4
iframe.html?selectedKind=Task&selectedStory=archived:1 OTS parsing error: invalid version tag
iframe.html?selectedKind=Task&selectedStory=archived:1 Failed to decode downloaded font: http://localhost:9009/icon/percolate.woff?5w3um4
iframe.html?selectedKind=Task&selectedStory=archived:1 OTS parsing error: invalid version tag
iframe.html?selectedKind=Task&selectedStory=archived:1 Failed to decode downloaded font: http://localhost:9009/icon/percolate.ttf?5w3um4
iframe.html?selectedKind=Task&selectedStory=archived:1 OTS parsing error: invalid version tag
iframe.html?selectedKind=Task&selectedStory=archived:1 Failed to decode downloaded font: http://localhost:9009/icon/percolate.ttf?5w3um4
iframe.html?selectedKind=Task&selectedStory=archived:1 OTS parsing error: invalid version tag
```

**Comment by domyen** [comment]
Doesn't appear to be reproduced given that we're seeing a lot of readers load fonts successfully. Closing.

**Comment by hirankit** [comment]
Adding Storybook Using:

`npx -p @storybook/cli sb init`

will have:

_package.json_
`  "scripts": {
    "storybook": "start-storybook -p PORT_NUMBER"
  }`

but to have Storybook serving static assets from folder: ./public, we need:

_package.json_
`  "scripts": {
    "storybook": "start-storybook -s ./public -p PORT_NUMBER"
  }`

**Comment by tmeasday** [comment]
@hirankit I just followed the steps in the guide and I end up:

```
    "storybook": "start-storybook -p 9009 -s public",
```

I wonder what command you ran?
