### ISSUE TITLE
Redux usage examples are very confusing and should be rewritten

### ISSUE THREAD

**Issue by markerikson** [chromaui/learnstorybook.com#531]
Hi, I'm a Redux maintainer. A Redux user just pointed me to https://storybook.js.org/tutorials/intro-to-storybook/react/en/data/ , which contains the following Redux reducer example:

```js
// All our reducers simply change the state of a single task.
function taskStateReducer(taskState) {
  return (state, action) => {
    return {
      ...state,
      tasks: state.tasks.map(task =>
        task.id === action.id ? { ...task, state: taskState } : task
      ),
    };
  };
}

// The reducer describes how the contents of the store change for each action
export const reducer = (state, action) => {
  switch (action.type) {
    case actions.ARCHIVE_TASK:
      return taskStateReducer('TASK_ARCHIVED')(state, action);
    case actions.PIN_TASK:
      return taskStateReducer('TASK_PINNED')(state, action);
    default:
      return state;
  }
};
```

While this code runs, it is very unconventional. I've never seen a pattern where a reducer returns other reducers in the form of closures, and it's never been something we've ever shown in our docs.  This could easily be rewritten to be much clearer.

On top of that, the form of Redux logic shown here is very outdated. We now teach Redux Toolkit as the default approach for writing Redux logic:

- https://redux.js.org/tutorials/fundamentals/part-8-modern-redux
- https://redux.js.org/tutorials/essentials/part-2-app-structure

I realize that teaching Redux isn't the focus of this page, but I'd really appreciate it if you could update this page to show more standard Redux patterns in some way - either switching to use `createSlice` from Redux Toolkit, or at least removing the strange "closure reducer" pattern and just handling the logic directly inside of `taskStateReducer`.

**Comment by jonniebigodes** [comment]
@markerikson wow, thanks for reaching out to us on this. And indeed you're right on this. That section of the documentation is been a bit left behind for a bit. I've been actually considering updating it in an upcoming pull request. But and I hope you don't take it the wrong way, as you're one of the maintainers and probably know better how to best document this section and what best practices to apply in this case, if you wouldn't mind making a pull request and supply the implementation in the form of a sample repository with the tutorial and ping me I'd appreciate it. Sounds good?

Looking forward to it.

Stay safe

**Comment by markerikson** [comment]
Sure. A really short example might be:

```js
import { configureStore, createSlice } from '@reduxjs/toolkit';

const tasksSlice = createSlice({
  name: 'tasks',
  initialState: [],
  reducers: {
    taskStateUpdated(state, action) {
      const {id, status} = action.payload
      const task = state.find(task => task.id === id);
      if (task) {
        task.state =  status
      }
    }
  }
})

export const { taskState } = tasksSlice.actions;

const store = configureStore({
  reducer: tasksSlice.reducer
})
```

Changes:

- `configureStore` instead of `createStore`
- `createSlice` instead of a hand-written reducer
- since both action cases in the original example are just "find the one task by ID and update its `state` field", I rewrote this to be a single action case that expects an action like `{type, payload: {id, status}}`, and you'd dispatch it as: `dispatch(taskStateUpdated({id: task.id, status: 'TASK_ARCHIVED'})` or similar.

**Comment by markerikson** [comment]
It's also worth noting that we no longer teach the "container/presentational" pattern in our docs, especially now that we do teach the React-Redux hooks API as the default instead of `connect`.  Some quick references:

- https://redux.js.org/tutorials/fundamentals/part-5-ui-react
- https://redux.js.org/tutorials/essentials/part-2-app-structure
- [The Tao of Redux, Part 2: Practice and Philosophy](https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/)
- [Redux Fundamentals Workshop Slides](https://blog.isquaredsoftware.com/2018/06/redux-fundamentals-workshop-slides/)

Not sure I have time to do an actual PR and update the docs myself, but hopefully that provides some pointers to the approaches we currently recommend, and I'm happy to answer if there's more questions here. (also I tweeted this issue earlier today, and hopefully someone else might pop in and offer to do the actual PR work.)

**Comment by cwatsonc** [comment]
> It's also worth noting that we no longer teach the "container/presentational" pattern in our docs, especially now that we do teach the React-Redux hooks API as the default instead of `connect`. Some quick references:
> 
> * https://redux.js.org/tutorials/fundamentals/part-5-ui-react
> * https://redux.js.org/tutorials/essentials/part-2-app-structure
> * [The Tao of Redux, Part 2: Practice and Philosophy](https://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/)
> * [Redux Fundamentals Workshop Slides](https://blog.isquaredsoftware.com/2018/06/redux-fundamentals-workshop-slides/)
> 
> Not sure I have time to do an actual PR and update the docs myself, but hopefully that provides some pointers to the approaches we currently recommend, and I'm happy to answer if there's more questions here. (also I tweeted this issue earlier today, and hopefully someone else might pop in and offer to do the actual PR work.)

The container-representational references in the prose are out-of-date; one points to an article that states they no longer ascribe to that methodology for various reasons -- @jonniebigodes thanks for pointing these out -- it took me the longest time to sort through the redux constructs on the tutorial -- IMO it could be removed/refactored to good effect.

**Comment by jonniebigodes** [comment]
Closing this issue as the tutorial has been updated accordingly and is featuring Redux Toolkit.

**Comment by kp1129** [comment]
> ```js
> reducers: {
>     taskStateUpdated(state, action) {
>       const {id, status} = action.payload
>       const task = state.find(task => task.id === id);
>       if (task) {
>         task.state =  status
>       }
>     }
>   }
> ```

@markerikson I see this is a closed issue, but I'm curious -- is this pattern updating state directly, with task.state = status, or is the reducer returning new state under the hood? i would have expected the taskStateUpdated function to return a copy of state with updated task replacing the old one, but not sure if that's an old React pattern. As is, it looks like it's mutating state directly and returns undefined.

**Comment by markerikson** [comment]
@kp1129 Exactly!  You do still have to return an immutably updated state...

but Redux Toolkit uses the Immer library inside.  It wraps your state in an ES2015 `Proxy`, so you can write what _appears_ to be "mutating" code, and Immer automatically turns that into a safe and correct immutable update.

Both the React and Redux specifically recommend Immer as the best way to write immutable updates today:

- https://react.dev/learn/updating-objects-in-state#write-concise-update-logic-with-immer
- https://redux.js.org/tutorials/essentials/part-2-app-structure#reducers-and-immutable-updates
- https://redux-toolkit.js.org/usage/immer-reducers

**Comment by kp1129** [comment]
@markerikson Thank you so much for your quick and thorough response! 🙏
