### ISSUE TITLE
wrong css file text for  angular tutorial , import missing

### ISSUE THREAD

**Issue by bodote** [chromaui/learnstorybook.com#537]
## Corrections for Angular: https://storybook.js.org/tutorials/intro-to-storybook/angular/en/simple-component/

- `src/index.css`-> `src/styles.css`
- `.storybook/preview.js` : `+ import "import '../src/styles.css';"`

**Comment by jonniebigodes** [comment]
@bodote that's correct, as I've mentioned previously you don't need to make any changes to the `.storyboook/preview.js`, as it's already picking up the styling with Angular. We can mitigate this and adjust the tutorial accordingly, which in this case would be something like 

"The additional markup from above combined with the existing CSS yields the following UI: "

Or something similar. 

If you're ok with making a pull request and making this small but rather important change to the tutorial we'd appreciate it. Let me know and we'll go from there.

Have a great day!

Stay safe

**Comment by jonniebigodes** [comment]
@bodote hope you don't mind but I'm closing this issue as the tutorials were updated with a recent pull request. But to avoid all of your work going to waste, what I would like from you is the following. If you could make a new pull request and update the readme with the Instructions for Apple's M1 we'd appreciate it. 

Let me know once the pull request is up and we'll go from there.


Have a great day!


Stay safe
