### ISSUE TITLE
Question vue tutorial broken

### ISSUE THREAD

**Issue by travis5491811** [chromaui/learnstorybook.com#54]
Everything was ok until i got to https://www.learnstorybook.com/vue/en/data/

This section and forward:

> Then we'll update our TaskList to read data out of the store. First let's move our existing presentational version to the file src/components/PureTaskList (renaming the component to pure-task-list), and wrap it with a container in src/containers/TaskList.vue:

ERROR in ./src/components/PureTaskList
Module build failed: Error: ENOENT: no such file or directory, open '~./taskbox/src/components/PureTaskList'

To keep confusion down and amplify clarity can you list the filename above the code snips clearly?

filename.extension
```
...some code
```

Plus I'm working on the vue version, but towards the end of the page, the screenshot is a duplicate from the last chapter but should show task being pulled from the store. Then the jest example is written for react not vue.

**Comment by tmeasday** [comment]
Hi @travis5491811, thanks letting us know!

Do you feel like contributing a PR to fix these problems? In particular I think the text about moving the file could be clearer and obviously the test should be in vue not react! It seems you are more on top of this than me right now.

For the other note:
 1. @domyen could we put filenames at the top of code blocks? We might need some styles for that.
 2. Re: the gif being the same; this is intentional, all we've done is change the stories to use the pure version of the component so the behaviour should be the same. We didn't include a gif of the app running out of the store but that should work at this point.

**Comment by tmeasday** [comment]
Hi @travis5491811,

I've made some improvements in 8576514.

Hopefully this clears up the questions about file locations and also repairs the test. Let me know if that helps.

I realise that vue is changing quite quickly (and storybook 4 is about to come out) so I think I will need to revisit this in the next little bit but let me know any other problems you run into.

**Comment by travis5491811** [comment]
Thanks @tmeasday i tried again from the beginning of the tutorial today on a different machine.

`yarn test:unit` was successful but `yarn run storybook` threw the following error:

```
=> Loading custom .babelrc
=> Loading custom addons config.
=> Loading custom webpack config (full-control mode).
/home/travis/Desktop/taskbox/node_modules/webpack/lib/DefinePlugin.js:93
node_modules/webpack/lib/DefinePlugin.js:42
		compiler.hooks.compilation.tap(
		               ^

TypeError: Cannot read property 'compilation' of undefined
```

I think the above error is because vue storybook is broken (webpack 4 compatibility problem) and everybody is working on storybook 4.0.0.

Is vue storybook always based on latest as appose to LTS version of vue? The reason I'm asking is because trying to get started with vue storybook with a new project following tutorials is looking impossible. 

In some cases I can follow the same steps on one machine on one day and on another machine another day and things not work. Like today for example, I was blown away when I couldn't make it off the first page (Get started) but made it all the way to "Data" a few days ago.

What I'm trying to figure out is, when should I try vue storybook again?

**Comment by tmeasday** [comment]
Hi @travis5491811 -- I just tried following the instructions from https://www.learnstorybook.com/vue/en/get-started and it worked just fine on my machine. 

Here's the `package.json` I ended up with if it helps:

```
{
  "name": "taskbox",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.5",
    "@vue/cli-plugin-eslint": "^3.0.5",
    "@vue/cli-plugin-unit-jest": "^3.0.5",
    "@vue/cli-service": "^3.0.5",
    "@vue/eslint-config-prettier": "^3.0.5",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
    "vue-template-compiler": "^2.5.17",
    "@storybook/vue": "^3.4.11",
    "@storybook/addon-actions": "^3.4.11",
    "@storybook/addon-links": "^3.4.11",
    "@storybook/addons": "^3.4.11",
    "babel-preset-vue": "^2.0.2"
  }
}
```

**Comment by travis5491811** [comment]
Hey @tmeasday thanks for that, I have a matching file. I also removed my global node_modules just in case.
I'm not sure if it matters or not but just in case, what is your node version? I'm running
```
$ nvm install node
v10.12.0 is already installed.
Now using node v10.12.0 (npm v6.4.1)
```
I haven't had a chance to check the other machine I used where everything worked up to the "data" section.

**Comment by tmeasday** [comment]
I would have been using node 8, but I sort of doubt that would affect the webpack version storybook ends up using (which seemed to be the issue in what you linked above)
