### ISSUE TITLE
[Tutorials] Intro to Storybook -- issue with broken test following app wiring step in "Screens" section

### ISSUE THREAD

**Issue by cwatsonc** [chromaui/learnstorybook.com#553]
In the 5th(?) chapter/section (Screens) a step to wire the app to the newly finished InboxScreen implementation misses a test upgrade to App.test.js which breaks the test run.  Either warn the students or add a note to change this test in the same section. 

Changing the test description and modifying the assertions fixed this issue for me.

**Comment by jonniebigodes** [comment]
@cwatsonc thanks for reaching out to us with your issue, we appreciate it. We're aware of the fact and that omission is already covered. A recent pull request was merged with some additions to the tutorial and with that I included what you mentioned in this pull request.


Feel free to reach out to us with any other issues you encounter with our tutorials we appreciate the feedback and always looking for improvements.

Going to close this issue if you don't mind.

Have a great day.


Stay safe
