### ISSUE TITLE
Tutorial: presentation of the project in the tutorial 

### ISSUE THREAD

**Issue by 552020** [chromaui/learnstorybook.com#602]
Despite the CDD approach, maybe it would be good to just shortly present in one sentence in the section [Build a simple component](https://storybook.js.org/tutorials/intro-to-storybook/react/en/simple-component/) the mini-app, which the learners are going to build through the tutorial.

**Comment by jonniebigodes** [comment]
Thanks for reaching out to us with your question, hope you don't mind but I'm going to close this as the tutorial will go through some rework during the upcoming weeks.

Hope you have a great weekend!

Stay safe
