### ISSUE TITLE
Import library name is outdated

### ISSUE THREAD

**Issue by smilee** [chromaui/learnstorybook.com#603]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/5793796/168928661-7ba036a4-e485-4059-a3a7-436a80393837.png">

@storybook/api should be @storybook/addons

**Comment by smilee** [comment]
https://github.com/chromaui/learnstorybook.com/pull/604

**Comment by jonniebigodes** [comment]
@smilee thanks for taking the time to open up the issue and pr. Sadly I had to close and will do the same here. Hope you understand but the change you proposed would lead to an issue with the tutorial. 

Hope you have a great weekend.

stay safe
