### ISSUE TITLE
Not working URL for deployed storybook in tutorials intro to storybook (vue)

### ISSUE THREAD

**Issue by yfedyai** [chromaui/learnstorybook.com#610]
Hey, team
I am trying to work through the intro to storybook tutorial for vue and faced with the issue, on conclusion page https://storybook.js.org/tutorials/intro-to-storybook/vue/en/conclusion/ when trying to reach link with deployed storybook 
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/33098616/171998635-4d40fbca-2fa7-4861-994f-224a4f0c7aef.png">
I got error `Not Found - Request ID: 01G4QAFJP6ZNQ9SNE0DNVXCPQZ`

**Comment by jonniebigodes** [comment]
@yfedyai thanks for bringing this to our attention, we appreciate it. It seems that the deployed Storybook was once deployed on Netlify and that's not the case anymore. I've made a pull request addressing it.

Hope you have a great week.

Stay safe
