### ISSUE TITLE
React tutorial fails to build

### ISSUE THREAD

**Issue by fergusmeiklejohn** [chromaui/learnstorybook.com#632]
The learn storybook project is failing to build.
https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/

Project build error:
```
Failed to compile.

ERROR in ./src/App.js 1:40-140
Module not found: Error: You attempted to import /taskbox/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

**Comment by jonniebigodes** [comment]
@fergusmeiklejohn, thanks for taking the time to open up this issue. We appreciate it. Can you provide us with a bit more context on your environment so that this can be better triaged?

**Comment by jonniebigodes** [comment]
Closing this issue for now. Let me know if you're still running into this issue and I'll gladly re-open it and continue to work with you on it until we find a suitable solution that helps you go through the tutorial without any issues.
