### ISSUE TITLE
yarn start_error

### ISSUE THREAD

**Issue by lianglinux5** [chromaui/learnstorybook.com#64]
![yarn_start](https://user-images.githubusercontent.com/14293060/49639977-49a56c00-fa47-11e8-884a-afe4c2d36e8d.png)
yarn start error
 
Error: [BABEL] /Volumes/LaCie/react/taskbox/src/index.js: Cannot find module '@babel/plugin-syntax-jsx' (While processing: "/Volumes/LaCie/react/taskbox/node_modules/babel-preset-react-app/index.js$1$0")

yarn version:1.10.1
nodejs version:v10.11.0

**Comment by tmeasday** [comment]
Hi @lianglinux5 -- this looks to me like maybe `yarn` hasn't installed properly. Perhaps try `yarn` again?
