### ISSUE TITLE
Vue - Intro to Storybook - Needed to change Task.vue to multi-word file name

### ISSUE THREAD

**Issue by bubbzDotDev** [chromaui/learnstorybook.com#652]
I just finished the tutorial and only had one issue along the way. Received an error that `Task.vue` needed to be more than one word. I changed mine to `TheTask.vue`. If that sounds like a good change, let me know. I don't mind submitting a pull request.

**Comment by jonniebigodes** [comment]
@bubbzDotDev, thanks for reaching out to us with your issue we appreciate it. And sorry for the issue you've encountered with our tutorial. I've checked, and with the latest update made, I forgot about updating the snippet used in the Simple Component section. This is a trivial task that I was going to address tomorrow morning my time. To give you a bit of a context, this is something that you solve by updating the component to:

```js
// Task.vue

// Template goes here
export default {
  // eslint-disable-next-line vue/multi-word-component-names 👈 Disables eslint rule for the component name
  name: 'Task',
}
</script>
```

I'm aware of the rule usage implemented to only add a single named component name for root components (e.g., App). But to keep things simple, we can use this approach and solve it. If this were a more in-depth tutorial centered around Vue specifics for sure, we would factor in this rule.

Hope you have a great day.

Stay safe.
