### ISSUE TITLE
"Error: error:0308010C:digital envelope routines::unsupported" during build for Design Systems for Developers tutorial

### ISSUE THREAD

**Issue by bubbzDotDev** [chromaui/learnstorybook.com#656]
On chapter 3 of Design Systems for Developers tutorial. Receiving the following error when it's 99% done after running `yarn storybook`:
```
ModuleBuildError: Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
```
The `error:0308010C` error is widely reported across many packages. I've tried a number of things and interested if anyone's found a fix for when it occurs when trying to run Storybook.

Some things I've tried:

- Updating dependencies: `yarn upgrade-interactive --latest`
- Switching to webpack5:
```
// package.json
"devDependencies": {
    "@storybook/builder-webpack5": "^6.5.12",
    "@storybook/manager-webpack5": "^6.5.12"
  }
  
// .storybook/main.js
module.exports = {
  core: {
    builder: "webpack5"
  }
}
```
- Adding `--openssl-legacy-provider` to `"storybook":` script in package.json. I tried a few different ways but received different errors related to where I inserted it so not sure where it would go if it is a workaround for this.

**Comment by jonniebigodes** [comment]
Closing this issue for now. Let me know if you're still running into this issue and I'll gladly re-open it and continue to work with you on it until we find a suitable solution that helps you go through the tutorial without any issues.
