### ISSUE TITLE
Grammatical mistakes in Spanish translation

### ISSUE THREAD

**Issue by shogohida** [chromaui/learnstorybook.com#662]
I found 4 grammatical mistakes in Spanish translation. "componente simples" should be "componente simple" because the noun is singular and the adjective also must be singular.

https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/vue/es/simple-component.md
https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/svelte/es/simple-component.md

**Comment by jonniebigodes** [comment]
Closing this per comment in the associated pull request.
