### ISSUE TITLE
Publishing component library as NPM package

### ISSUE THREAD

**Issue by Prasanna-Poonacha** [chromaui/learnstorybook.com#67]
The whole concept of storybook, component library and using in the application is very cool. I was looking at something which could be used in other projects too as a npm package and use the components from the component library. Is there a way to do it ?

**Comment by icarlossz** [comment]
Yes, it can. There a lot of medium articles about it, I think its a good idea put something about it in learnstorybook.

**Comment by Prasanna-Poonacha** [comment]
I did see lot of posts in medium. Different ways. It really makes sense to put in learnstorybook and relates really well. I request to put something. I am following react learnstorybook. Every looks really great. But I want to publish and use it in other projects too.

**Comment by icarlossz** [comment]
In my job we have a storybook library published in npm for all the projects that follows the same styleguide, you can find how to do it in any medium article like I told you. And there should definitely be something for that in this tutorial.

**Comment by Prasanna-Poonacha** [comment]
Sure. Which job ?

**Comment by icarlossz** [comment]
I work at Walmart, all that stuff is private, sorry.

**Comment by Prasanna-Poonacha** [comment]
I get it. Thank you :)

**Comment by domyen** [comment]
That'd be an awesome resource for the Storybook community!

Publishing to NPM is a bit more advanced than what people just getting started with Storybook are looking for so it probably doesn't belong in this edition of LearnStorybook.com. Typically, the practical time for a team to publish a library is when other product teams start using it. 

Perhaps it's time for a **sequel** to LearnStorybook that covers advanced topics for professional teams. One that goes over the production-grade workflows used by mature teams. I have some ideas, would you be interested in helping out @icarlossz @Prasanna-Poonacha?

**Comment by Prasanna-Poonacha** [comment]
Sure. I am in too @domyen :)

**Comment by domyen** [comment]
I'm going to close this because publishing Taskbox's components isn't in the scope of this guide. I'm going to make another issue to document "advanced" topics for the sequel to Learn Storybook.
