### ISSUE TITLE
ReferenceError: module is not defined in ES module scope

### ISSUE THREAD

**Issue by mmt5567** [chromaui/learnstorybook.com#673]
**After setting up with [get start ](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/)

I have run the "yarn storybook" command and getting the below error.**

ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/mmt5567/Documents/workspace/gommtRNtaskbox/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/mmt5567/Documents/workspace/gommtRNtaskbox/babel.config.js:1:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./storybook/addons.js ./node_modules/@storybook/react-native-server/dist/client/manager/index.js main[1]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.34 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.14 KiB {HtmlWebpackPlugin_0} [built]
WARN Unable to close preview build!

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Comment by jonniebigodes** [comment]
@mmt5567, thanks for taking the time and effort to reach out to us with your issue. We appreciate it. To give you some context on this. the tutorial is quite outdated, and issues like this one are more than bound to happen. We're in discussions with the React Native maintainer to see how best to proceed on this as he's gearing towards an update to the React Native version, and with that, this tutorial will also finally be updated. If you're willing, might I interest you in checking out the [Storybook React Native](https://github.com/storybookjs/react-native/) repo and helping the maintainer out?

Hope you have a great weekend!

Stay safe

**Comment by jonniebigodes** [comment]
Closing this for now. Feel free to ping me if you wish to continue to work on this. 

Hope you have a great weekend.

Stay safe
