### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]

### ISSUE THREAD

**Issue by mmt5567** [chromaui/learnstorybook.com#674]
**After setting up with [get start](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/)

I have run the "yarn web" command and getting the below error.**

yarn run v1.22.18
$ expo start --web -p 9999
Starting project at /Users/mmt5567/Documents/workspace/gommtRNtaskbox
(node:5903) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received 65536.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:6:10)
    at availableAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:24:17)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:37:23
    at new Promise (<anonymous>)
    at freePortRangeAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:33:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jonniebigodes** [comment]
@mmt5567 thanks for reaching out to us with your issue. For this particular one, it seems that it's a bit of an issue on Expo's side of things not actually with Storybook itself, and I hope you don't take it the wrong way this one will be closed. I saw that you opened up another issue here, and let's continue the discussion there.
