### ISSUE TITLE
Dependency issue: UI testing handbook > react > automate

### ISSUE THREAD

**Issue by pereng11** [chromaui/learnstorybook.com#696]
Hello, I'm very appreciate for providing helpful guide.

I found a dependency issue with github-actions CI process.

That's the error I've seen in 'user-flow' job in github-actions while following the tutorial.
<img width="1014" alt="스크린샷 2023-03-23 오후 4 10 41" src="https://user-images.githubusercontent.com/67821588/227129531-59c7f790-205d-4d8b-a43a-460f13fbf8a5.png">

I resolved that by changing the version of `cypress-io/github-action`from `@v2` to `@4.1.0`  in `./github/workflows/ui-tests.yml`, thanks for @developer-ocansey on https://github.com/cypress-io/github-action/issues/568 

In previous step 'User flow', I installed cypress by `npm i -D cypress` and I think that's why the dependency issue occured(Installing latest version).

I hope it helps others who have the same problem as me.

Thank you for your works and hope you have a good day.

**Comment by jonniebigodes** [comment]
@pereng11 thanks for bringing this to our attention. Appreciate it 🙏 ! I'm going to close this out as with the changes required for Storybook 7.0 this issue was addressed and it's now not longer an issue.

Hope you have a great day

Stay safe
