### ISSUE TITLE
Vue tutorial no longer has jest

### ISSUE THREAD

**Issue by headphonejames** [chromaui/learnstorybook.com#701]
The sample app template in https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/ has been updated to vite. It no longer includes a sample jest test, nor does it support the "yarn test:unit" script. The three modalities no longer applies to this sample app.

Also, "yarn serve" is now "yarn dev".  Thanks

**Comment by jonniebigodes** [comment]
@headphonejames, thanks for taking the time to open this issue and reach out to us. I'm aware of it, as the React & Vue versions are being updated to the latest Storybook release. The template was first updated to provide the starting point for the code behind the tutorial. 

I hope you don't take it the wrong way, but I will close this. The updated version should be up sometime next week.

I hope you have a great weekend.

Stay safe
