### ISSUE TITLE
Persian translation

### ISSUE THREAD

**Issue by SamAbaasi** [chromaui/learnstorybook.com#721]
Hi!
How can I help to translate the Storybook into Persian? (all tutorials in this [link](https://storybook.js.org/tutorials/))
Thanks!

**Comment by jonniebigodes** [comment]
Hey @SamanAbasi, and sorry for the delayed response. We'd like that very much. I suggest starting with the Intro to Storybook tutorial, choosing the framework you're more comfortable with, and taking it from there. Sounds like a reasonable plan to you.

Also, a reminder that you didn't need to open up an issue specifically for your request. We have a dedicated issue (#3) to help with the community translation efforts. 


Looking forward to seeing the pull request so we can follow up on it.

Have a great day.

Stay safe

**Comment by samanabasi** [comment]
Hello! 😊

Thank you for your response and guidance. I'm glad that this suggestion was approved for us. I will definitely start studying the "Intro to Storybook" tutorial and will proceed step by step.

I understand that there’s no need to open a new issue, and I appreciate your reminder. I will submit the pull request soon.

Have a great day and take care of yourself! 🌟
