### ISSUE TITLE
diffrences

### ISSUE THREAD

**Issue by pranaythota** [chromaui/learnstorybook.com#80]
what are the diffrences between testing tool storybook and mocha or jest

**Comment by jonniebigodes** [comment]
@pranaythota to my knowledge none whatsoever. I'm inclined to believe that jest was chosen as a preference, i haven't fully tested it with mocha...it's been on the "back burner" (pardon the bad pun) for quite a while

**Comment by tmeasday** [comment]
@pranaythota do you mean the difference between storybook and jest say?

Maybe this article (which talks about component explorers, storybook being the best example) could help: https://blog.hichroma.com/the-crucial-tool-for-modern-frontend-engineers-fb849b06187a
