### ISSUE TITLE
Vue with TypeScript Example Configs Missing

### ISSUE THREAD

**Issue by ux-engineer** [chromaui/learnstorybook.com#92]
TypeScript is coming fast for Vue. Already at this point, it may not be such a good idea to start a new Vue project without TypeScript...

Could you please update Vue tutorial to show proper configurations for working with TypeScript also?

**Comment by shilman** [comment]
@tmeasday Let's get the typescript presets released and into LearnStorybook!

**Comment by jeanphibaconnais** [comment]
Hi,
I would like to look and test Vuejs3 on a new project, so I could look this issue and change the vue part with typescript

**Comment by jonniebigodes** [comment]
@jeanphibaconnais thank you for interest on updating the tutorial for vue 3. There's still a bit of work to be done on how Storybook will function with Vue 3. But as soon as we have a stable version for it. We'll let you know and we would be glad to include it the tutorial.

**Comment by jonniebigodes** [comment]
Closing this issue as the tutorial is already updated
