### ISSUE TITLE
Storybook Guide for React Native

### ISSUE THREAD

**Issue by lyqht** [chromaui/learnstorybook.com#96]
I think it will be great if there is a guide for React Native Storybook! There is a massive lack of guides on RN, and right now, there are vast differences in terms of expectations and implementations of Storybook for React vs React Native which the current Storybook website fails to highlight.
e.g. 
- Deployment of the Storybook as a static web app (buildstorybook does not exist for RN)
- Interface configuration of Storybook on RN
- Implementing add-ons on RN (in the official docs, they only mentioned the list of add-ons available but not how to use them on RN)
- The experience of running Storybook web on localhost together with iOS/Android Simulator is different than what the example on React showed. On RN, from what I have tried, you can click on different stories on the localhost and it only shows up on the simulator. The web unfortunately does not show the component itself.

**Comment by jonniebigodes** [comment]
@lyqht sorry for the late response, but for me personally i don't see why it shouldn't exist. If you're willing to do so, it's fine by me. If you don't mind, just follow the same structure outlined for every other framework present and make a pull request. Sounds good?

**Comment by lyqht** [comment]
Alright! i'll get to it once im done learning and implementing the various features of Storybook :)

**Comment by domyen** [comment]
Stoked for this @lyqht!
